import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { test } from 'node:test';
import { HELP_ARTICLES } from '../helpContent';

/**
 * T21b — every button in the UI is described somewhere in the help, and so is every knob that
 * has no button at all.
 *
 * <p>The audit that produced this file found six commands nobody had ever written a sentence
 * about — Sign Out, Move to Folder…, Show Signing Fingerprint…, Accept All…, Show What Changed,
 * Revoke Code Access… — plus a whole missing Trash article, in a catalog that had been reviewed
 * twice. A one-off audit finds that once; this test finds it on the commit that adds the next
 * command, which is the only moment it is cheap to fix.</p>
 *
 * <p><b>The shape is a forced choice, not a pass mark.</b> A command clears this test one of
 * three ways: the help names it verbatim, an ALIAS declares the words the help uses instead, or
 * SELF_EVIDENT declares — in a sentence, on the record — why it needs no article. There is no
 * fourth way and no silent default, so a new command cannot merely be forgotten: it fails until
 * somebody decides which of the three it is.</p>
 */

interface Manifest {
  contributes: {
    commands: Array<{ command: string; title: string }>;
    configuration: { properties: Record<string, unknown> };
  };
}

const manifest = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', '..', 'package.json'), 'utf8'),
) as Manifest;

/** Every English word of every article, lowercased — the corpus a reader actually gets. */
const corpus = HELP_ARTICLES.map((a) => Object.values(a.en).join(' '))
  .join(' ')
  .toLowerCase();

/** A menu title as prose: no trailing ellipsis (either spelling), no parenthetical aside. */
function asProse(title: string): string {
  return title
    .replace(/(\.\.\.|…)\s*$/u, '')
    .replace(/\s*\(.*?\)\s*$/u, '')
    .trim()
    .toLowerCase();
}

/**
 * The help says it in different words. The phrase is the assertion: rewrite the article and drop
 * the phrase, and this goes red rather than quietly losing the coverage.
 */
const ALIAS: Record<string, string> = {
  'credSshManager.addEntity': 'add entry',
  'credSshManager.connectSsh': 'connect opens a terminal',
  'credSshManager.connectDb': 'open it in your database client',
  'credSshManager.runCommand': 'run it with one click',
  'credSshManager.runScript': 'variables pulled out as rows',
  'credSshManager.startVpn': 'start and stop the tunnel from the tree',
  'credSshManager.stopVpn': 'start and stop the tunnel from the tree',
  'credSshManager.generateSecret': 'generated by one button in the form',
  'credSshManager.closeRemoteBridge': 'the menu item shows close while a bridge runs',
  'credSshManager.backupToNas': 'snapshot vault now',
  'extension.exportSecrets': 'snapshot vault now',
  'extension.importSecrets': 'import / restore',
};

/**
 * No article, and that is the answer rather than a gap. Each reason has to survive being read
 * out loud: "a Refresh button refreshes" does; "we ran out of time" does not.
 */
const SELF_EVIDENT: Record<string, string> = {
  'credSshManager.refresh': 'A Refresh item re-reads the tree. There is nothing about it to learn.',
  'credSshManager.clearSearch':
    'The inverse of the filter, one click away from it, and described in the filter article by being its opposite.',
  'credSshManager.copyCommand':
    'Copy on a saved command copies the command. The terminal entry it belongs to is described in basics.',
  'credSshManager.showCommand':
    'Shows the command and its notes read-only — the same content the entry form holds, without the form.',
  'credSshManager.removeKeyFromAgent':
    'The inverse of Add to SSH Agent, which the ssh-agent article describes in full; unloading has no behaviour of its own.',
  'credSshManager.removeSecurityKey':
    'The inverse of Add Security Key, described in the protection article; removal is that same act undone.',
  'credSshManager.removeRecoveryCode':
    'The inverse of Set Up Recovery Code, described in the recovery-code article; removal is that same act undone.',
};

/** The three ways a command clears this test, in the order they are decided. */
function isCovered(command: string, title: string): boolean {
  if (SELF_EVIDENT[command] !== undefined) {
    return true;
  }
  const alias = ALIAS[command];
  if (alias !== undefined) {
    return corpus.includes(alias);
  }
  return corpus.includes(asProse(title));
}

test('every command in the manifest is described in the help, or declared self-evident', () => {
  const undocumented: string[] = [];
  for (const { command, title } of manifest.contributes.commands) {
    if (!isCovered(command, title)) {
      undocumented.push(`${command} — "${title}"`);
    }
  }
  assert.deepEqual(
    undocumented,
    [],
    `a command with no help article, no alias and no self-evident reason:\n${undocumented.join('\n')}`,
  );
});

test('an alias points at words the help really uses — a rewritten article cannot silently drop it', () => {
  for (const [command, phrase] of Object.entries(ALIAS)) {
    assert.ok(corpus.includes(phrase), `${command}: the help no longer says "${phrase}"`);
  }
});

test('the two lists carry no stale entry — a removed command leaves no excuse behind', () => {
  const commands = new Set(manifest.contributes.commands.map((c) => c.command));
  for (const command of [...Object.keys(ALIAS), ...Object.keys(SELF_EVIDENT)]) {
    assert.ok(commands.has(command), `${command} is listed here but no longer exists in the manifest`);
  }
  for (const [command, reason] of Object.entries(SELF_EVIDENT)) {
    assert.ok(reason.trim().length > 40, `${command}: the reason has to say something`);
    assert.ok(ALIAS[command] === undefined, `${command} is in both lists — decide which`);
  }
});

/**
 * The other half of the audit: a setting has no button to right-click, so nothing about it is
 * discoverable by exploring. Either the help explains what it does, or the entry here says why
 * the Settings-UI description is the whole story.
 */
const SETTING_COVERAGE: Record<string, string> = {
  'credSshManager.nasBackupPath': 'set sync location',
  'credSshManager.accountNasPaths': 'set sync location',
  'credSshManager.backupLocation': 'set backup location',
  'credSshManager.accountBackupPaths': 'set backup location',
  'credSshManager.backupIntervalHours': 'backupintervalhours',
  'credSshManager.accountBackupIntervals': 'set backup schedule',
  'credSshManager.backupRetainDays': 'retention is what keeps it bounded',
  'credSshManager.autoLockMinutes': 'auto-lock',
  'credSshManager.secretClipboardTtlSeconds': 'secretclipboardttlseconds',
  'credSshManager.agentGrantIdleMinutes': 'agentgrantidleminutes',
  'credSshManager.agentGrantMaxCalls': 'agentgrantmaxcalls',
  'credSshManager.maskAgentOutput': 'masked on its way out',
  'credSshManager.gitDeployKeys': 'gitdeploykeys',
  'credSshManager.breachCheck': 'breach check',
  'credSshManager.wslAgentRelay': 'relay',
  'credSshManager.autoSync': 'a sync pulls, merges, commits and pushes on its own',
  // Declared, not described: plumbing whose Settings-UI text is complete on its own.
  'credSshManager.autoSyncIntervalMinutes':
    'REASON: the interval of a sync the help already explains; a number of minutes teaches nothing further.',
  'credSshManager.wslRelayCommand':
    'REASON: how creds is spelled inside WSL — a path, touched only when the default name is wrong, and the setting says so.',
  'credSshManager.wslRelayDistros':
    'REASON: which distributions get the socket; the relay article covers the feature, the list is deployment detail.',
  'credSshManager.dbExtensions':
    'REASON: an override mapping a DB type to the extension that opens it. Nothing happens until a default is wrong.',
  'credSshManager.readCliHelp':
    'REASON: a convenience while typing a terminal entry — it reads --help to label flags. No security or storage consequence.',
  'credSshManager.googleClientId':
    'REASON: your own OAuth client id, needed only when self-hosting sign-in; the setting names the console page it comes from.',
  'credSshManager.microsoftApiScope':
    'REASON: an Entra app registration scope, supplied by whoever runs the tenant, never chosen by the reader of help.',
  'credSshManager.uiScale':
    'REASON: the plus/minus control sits on every page; the setting only remembers where you left it.',
  'credSshManager.helpLanguage':
    'REASON: the language switch is at the top of the help page itself — the page explains it by being it.',
};

test('every setting is either explained in the help or carries a written reason it need not be', () => {
  const keys = Object.keys(manifest.contributes.configuration.properties);
  for (const key of keys) {
    const entry = SETTING_COVERAGE[key];
    assert.ok(entry !== undefined, `${key} is a setting nobody classified — describe it in the help or say why not`);
    if (entry.startsWith('REASON:')) {
      assert.ok(entry.length > 60, `${key}: the reason has to say something`);
      continue;
    }
    assert.ok(corpus.includes(entry), `${key}: the help no longer says "${entry}"`);
  }
  for (const key of Object.keys(SETTING_COVERAGE)) {
    assert.ok(keys.includes(key), `${key} is classified here but is no longer a setting`);
  }
});
