import { HelpBody } from './helpContent';

/**
 * German bodies, one entry per article id.
 *
 * <p>Written against the English article rather than word for word: the catalog's shape is what
 * carries — what it is, why, how to set it up, how to use it, what can go wrong — and a sentence
 * that reads as a translation reads as a translation. Command names, setting keys and menu entries
 * stay in English, because that is what the person sees on screen.</p>
 *
 * <p>An article missing from this map falls back to English VISIBLY, which is the rule the catalog
 * has always had: a missing translation must never hide an article.</p>
 */
export const DE_BODIES: Readonly<Record<string, HelpBody>> = {
  'getting-started': {
    title: "Hier anfangen: ein Konto und der Ort, an dem sein Tresor lebt",
    whatItIs: "Ein Konto ist ein Tresor: eigener Baum, eigene Verschlüsselung, eigener Ort zum Leben. Eines anzulegen ist das Erste, was Sie tun — Ordner, Einträge und alles Weitere hängen daran.\n\nEin Tresor funktioniert vollständig auch ganz ohne Ort. Was ein Speicherort hinzufügt, ist eine zweite Maschine und andere Menschen.",
    why: "Alles wird auf Ihrer Maschine verschlüsselt, bevor es sie verlässt, der Ort hält also ausschließlich Geheimtext — die Wahl lohnt sich trotzdem am Anfang und nicht später, wenn schon mehrere Maschinen Kopien des alten Ortes halten.",
    setup: "Kontozeile -> **Add Account**, und anmelden. Dann auf diesem Konto -> **Set Sync Location…**, und eines von beidem wählen:\n\n- ein **Ordner** — jeder Pfad, den diese Maschine beschreiben kann: `Z:\\\\Backups`, `\\\\\\\\NAS\\\\Vault`, `/mnt/nas/vault`, oder ein Ordner, den etwas anderes bereits synchronisiert;\n- ein **Server** — die URL eines Cred Vault Server, `https://vault.company.com`.\n\nLassen Sie es leer, bleibt der Tresor auf dieser Maschine: alles funktioniert, nichts synchronisiert. Ein Git-Repository ist die dritte Möglichkeit und hat einen eigenen Artikel.",
    usage: "**Welches von beidem, und es ist keine Geschmacksfrage:**\n\n- Ein **Ordner**, wenn Sie es allein sind oder ein paar Leute, die ohnehin schon Speicher teilen. Nichts zu betreiben, nichts zu warten. Der Absender eines geteilten Eintrags gilt hier nach dem Prinzip Vertrauen beim ersten Kontakt — Sie lesen den Fingerabdruck einmal laut vor und merken ihn sich.\n- Ein **Server**, sobald mehr als eine Person beteiligt ist. Er stempelt den Absender einer Freigabe aus einer verifizierten Anmeldung, ein Absender lässt sich also nicht fälschen; er begrenzt Lesezugriffe auf Ihr eigenes Token; und Eintritt und Austritt folgen dem Identitätsanbieter, den Sie ohnehin haben.\n\nLesen kann keines von beiden. Was reist und was gespeichert wird, ist in beiden Fällen Geheimtext, und der Server hat keinen Schlüssel und keinen Codepfad, über den er einen bekäme.",
    whatCanGoWrong: "Ohne Speicherort ist nichts kaputt — der Tresor ist lokal und vollständig. Was fehlt, ist eine zweite Maschine oder das Teilen.\n\nDen Ort später zu ändern verschiebt die alte Datei nicht. Richten Sie den neuen auf denselben Ordner, oder synchronisieren Sie einmal von der Maschine, die die Daten noch hält.\n\n**Sign Out / Remove Account** nimmt das Konto von DIESER Maschine — den Baum, seine Tresordatei und die Schlüssel hier. Es ist keine Löschung auf dem Server oder im Sync-Ordner: melden Sie sich wieder an oder fügen Sie das Konto auf einer anderen Maschine hinzu, und der Baum ist zurück. **Reset Google OAuth** ist der kleinere Hammer für eine Anmeldung, die schiefgegangen ist — es vergisst das gespeicherte Client Secret und jede Google-Sitzung, lässt die Tresore in Ruhe, und die nächste Anmeldung beginnt sauber.\n\nBei einem Serverkonto liest **Server Metrics…** das eine JSON-Dokument, das der Server über sich selbst veröffentlicht. Wer nicht auf der Offiziersliste steht, bekommt die Absage des Servers, in Worten.\n\nEin Ort, der wie eine Git-Adresse aussieht — `git@…`, `ssh://…` oder eine Endung `.git` — wird ein Git-Tresor und kein Ordner. Das ist Absicht, und genau deshalb wird ein schlichtes `https://github.com/me/vault` NICHT erraten: es könnte ebenso gut eine Server-URL sein.",
  },
  'protection': {
    title: "Den Tresor abschließen: die PIN, ein Sicherheitsschlüssel, die Auto-Sperre",
    whatItIs: "Drei voneinander unabhängige Wege hinein und ein Timer, der entscheidet, wie lange ein entsperrter Tresor offen bleibt: eine **Sync-PIN**, ein oder mehrere **Sicherheitsschlüssel** (YubiKey / FIDO2) und ein gedruckter **Wiederherstellungscode**.",
    why: "Ein Tresor verschlüsselt seinen Inhalt mit einem zufälligen Hauptschlüssel, und dieser wird je Zugangsweg einmal eingepackt — eine Verpackung für die PIN, eine je registriertem Schlüssel. Jede Verpackung öffnet den Tresor, und deshalb verschlüsselt das Hinzufügen oder Entfernen eines Schlüssels Ihre Daten nie neu und macht die anderen nie ungültig.",
    setup: "- **Set Sync PIN** — dieselbe PIN auf jeder Maschine, die dieses Konto synchronisiert. Ohne sie lädt eine andere Maschine eine Datei herunter, die sie nicht öffnen kann.\n- **Add Security Key (YubiKey)…** in der Kontozeile. Das Betriebssystem zeigt seinen eigenen Dialog für Sicherheitsschlüssel, und das WebAuthn-PRF-Geheimnis des Schlüssels wird zum Verpackungsschlüssel. Registrieren Sie so viele, wie Sie möchten.\n- **Set Auto-Lock…** — Minuten IHRER Untätigkeit. 60 als Vorgabe; `0` sperrt nie.\n- **Set Up Recovery Code…** — der dritte Weg hinein, auf Papier. Hat einen eigenen Artikel, und lohnt sich, bevor Sie ihn brauchen.",
    usage: "Mit einem Schlüssel zu entsperren ist eine Berührung, im Stil einer Microsoft-Anmeldung — kein getipptes Passwort. Der Hauptschlüssel wird danach für das Fenster gehalten, die Hintergrundsynchronisation fragt also nie erneut. **Lock Vaults** verwirft ihn; **Unlock Vault (Security Key)…** fragt auf Wunsch.\n\nDie Auto-Sperre zählt IHRE Handlungen — Zugangsdaten öffnen oder kopieren, verbinden, einen Schlüssel installieren, bearbeiten, entsperren. Nicht Mausbewegungen und ausdrücklich nicht die Hintergrundsynchronisation: ein Fünf-Minuten-Timer, der als Aktivität zählte, hieße, dass das Leerlauffenster nie abläuft und die Einstellung stillschweigend nichts tut.\n\nSperren vergisst den Hauptschlüssel. Lokale Zugangsdaten funktionieren weiter, denn sie liegen im Schlüsselbund des Betriebssystems und sind nicht durch den Tresorschlüssel geschützt.",
    whatCanGoWrong: "Ohne PIN ist der Tresor praktisch lokal: eine andere Maschine kann die Datei herunterladen und nicht öffnen.\n\nDen letzten Sicherheitsschlüssel zu entfernen, wenn Sie die PIN vergessen haben, lässt den Wiederherstellungscode übrig — und sonst nichts. Das ist das Argument, ihn früh zu drucken.\n\n`autoLockMinutes: 0` sperrt nie. Das ist eine Möglichkeit, die jemand wollen kann, keine Vorgabe.",
  },
  'recovery-code': {
    title: "Der gedruckte Wiederherstellungscode",
    whatItIs: "Ein 150-Bit-Code, einmal gezeigt, gedruckt, auf Papier aufbewahrt — der dritte Weg in den Tresor für den Tag, an dem die PIN vergessen ist UND der Sicherheitsschlüssel weg.",
    why: "Die beiden alltäglichen Faktoren können gemeinsam ausfallen: eine vergessene PIN und ein verlorener YubiKey sind eine schlechte Woche, kein Paradox.",
    setup: "„Set Up Recovery Code…“ zeigt ihn einmal, mit Print und absichtlich ohne Copy: Zwischenablagen werden von Managern, Sync-Werkzeugen und Screenshot-Pipelines gelesen, und dieser Faktor muss das Notebook überleben.",
    usage: "„Unlock Vault (Recovery Code)…“, vom Papier abtippen — einen Tippfehler benennt die Prüfsumme lokal — und dann eine neue PIN setzen.",
    whatCanGoWrong: "Einen neuen Code zu erzeugen setzt den alten Ausdruck außer Kraft. Den letzten Sicherheitsschlüssel zu entfernen kann auch den Code außer Kraft setzen (das Neuverpacken braucht den Code, und der liegt auf Papier) — die Erweiterung sagt das inzwischen laut.",
  },
  'backup': {
    title: "Momentaufnahmen: datierte Kopien, die nie zusammengeführt werden",
    whatItIs: "Datierte Kopien des Tresors, in einen eigenen Speicher geschrieben, nach einem Zeitplan, den Sie wählen. Nicht dasselbe wie Synchronisation, und das mit Absicht.",
    why: "Synchronisation hält einen lebenden Tresor und FÜHRT ZUSAMMEN — was bedeutet, dass eine Löschung sich fortpflanzt. Löschen Sie Zugangsdaten auf dem Notebook, stimmt der nächste Abgleich am Desktop zu, dass sie weg sind. Für einen lebenden Tresor ist das richtig und als Sicherheitsnetz nutzlos, deshalb sind Momentaufnahmen ein zweiter, unabhängiger Weg, der nie zusammenführt und nie in jemandes Auftrag löscht.",
    setup: "- **Wohin** — `backupLocation`, oder pro Konto -> **Set Backup Location…**. Ein NAS-Ordner, eine externe Platte, **ein Google-Drive- oder OneDrive-Sync-Ordner** — alles, was diese Maschine beschreiben kann. Leer schaltet Momentaufnahmen ab.\n- **Wann** — `backupIntervalHours`: 24 täglich, 168 wöchentlich, `0` aus. Pro Konto -> **Set Backup Schedule…**. **Snapshot Vault Now** nimmt sofort eine auf.\n- **Wie lange** — `backupRetainDays`, 30 als Vorgabe; `0` behält alles.",
    usage: "**Momentaufnahmen funktionieren auch, wenn der Tresor auf einem Server liegt**, und die beiden sind absichtlich getrennte Einstellungen auf getrennten Speicher: ein Server ist der Dienst von jemandem, eine Momentaufnahme ist Ihre eigene Kopie Ihrer eigenen Daten.\n\nMomentaufnahmen in einen cloud-synchronisierten Ordner zu legen gibt Ihnen Verlauf außerhalb der Maschine, ohne irgendwem den Klartext zu geben — eine Momentaufnahme hat dasselbe verschlüsselte Format wie alles andere und öffnet sich mit dem Konto und der PIN.\n\nEine Momentaufnahme, die mit der vorherigen identisch ist, wird nicht geschrieben, ein stiller Tresor füllt also keinen kostenpflichtigen Ordner mit Kopien seiner selbst. Die neueste wird nie gelöscht, wie alt sie auch sei: ein Notebook, das ein Jahr zugeklappt war, darf nicht zu einem leeren Sicherungsordner zurückkehren.",
    whatCanGoWrong: "Momentaufnahmen an DENSELBEN Ort zu legen wie den Tresor hebt sie auf — das Sicherheitsnetz und das, was es auffangen soll, teilten sich einen Ausfall.\n\nMomentaufnahmen tragen Anhänge, Bilder und VPN-Konfigurationen ebenso wie Passwörter, der Ordner wächst also mit ihnen. Die Aufbewahrungsdauer ist das, was ihn begrenzt.",
  },
  'restore': {
    title: "Aus einer Momentaufnahme wiederherstellen",
    whatItIs: "Eine datierte Kopie zurück in ihr Konto lesen, aus dem ⋯-Menü des Baums -> **Import / Restore**.",
    why: "Die andere Hälfte des Sicherheitsnetzes. Eine Momentaufnahme, die niemand wiederherstellen kann, ist ein Ordner voller Dateien, und der Augenblick, in dem man merkt, dass sie sich nicht öffnet, ist nicht der Augenblick, in dem man sie braucht.",
    setup: "⋯ -> **Import / Restore**, die `.enc`-Datei wählen und beantworten, wonach gefragt wird. WELCHE Frage kommt, ist eine Eigenschaft der Datei, nicht des Befehls:\n\n- eine Momentaufnahme mit Schlüssel-Slots öffnet sich durch die eigene Tür des Tresors — eine Berührung des Sicherheitsschlüssels oder die PIN, dieselbe Tür, die auch die Synchronisation benutzt;\n- eine eigenständige Sicherung mit nur einem PIN-Slot verlangt die **Sicherungs-PIN, die beim Erstellen gesetzt wurde**, und eine Schlüsselberührung öffnet sie nicht. Der Dialog sagt das, denn sonst läse sich Schweigen so, als würde der Schlüssel ignoriert.",
    usage: "**Wiederherstellen ERSETZT den Baum dieses Kontos durch den der Momentaufnahme.** Es ist keine Zusammenführung: Einträge, die die Momentaufnahme nicht enthält, verschwinden samt ihren Geheimnissen. Genau das macht es zu einer Wiederherstellung und nicht zu einem Import — und deshalb probt man sicher an einem Wegwerfkonto und nicht an dem, das Sie benutzen.\n\nEine Momentaufnahme trägt alles: Anhänge, Bilder, VPN-Konfigurationen, Notizen und Versionsverlauf, nicht nur Passwörter.",
    whatCanGoWrong: "Eine Momentaufnahme aus einem neueren Build weigert sich, in einem älteren zu öffnen — *Unsupported backup version*. Erweiterung aktualisieren, dann wiederherstellen.\n\nLiegt das Konto an einem Sync-Ort, verbreitet eine alte Momentaufnahme mit anschließender Synchronisation genau diesen alten Zustand auf Ihre anderen Maschinen. Entscheiden Sie, welche Kopie die Wahrheit ist, bevor der nächste Abgleich läuft.",
  },
  'sync-vs-snapshots': {
    title: "Synchronisation und Momentaufnahmen sind verschiedene Maschinen",
    whatItIs: "Synchronisation führt eine verschlüsselte Datei pro Profil über Maschinen hinweg zusammen (kausal — zwei Maschinen, die gleichzeitig bearbeiten, laufen zusammen). Momentaufnahmen sind datierte Kopien, die nie zusammengeführt werden.",
    why: "Eine Zusammenführung pflanzt eine Löschung fort — das ist ihre Aufgabe. Die Momentaufnahme ist die Kopie, in der das Gelöschte noch steht.",
    setup: "Set Sync Location… pro Konto (Ordner, Server-URL oder ein Git-Repository). backupLocation auf ANDEREN Speicher richten. Dieselbe Sync-PIN auf jeder Maschine.",
    usage: "Sync Now, oder autoSync. Snapshot Vault Now für einen Punkt von Hand; Import / Restore, um zurückzukommen.",
    whatCanGoWrong: "Synchronisation und Momentaufnahmen in denselben Ordner hebt den Grund auf, warum es zwei gibt. Eine Wiederherstellung bringt den Tresor von DAMALS zurück — eine Synchronisation danach führt die neueren Änderungen wieder ein.",
  },
  'install-menu': {
    title: "Install… — was installiert wird und wohin",
    whatItIs: "Ein Untermenü, drei Installationen: die Terminal-CLI `creds` auf dieser Maschine, dieselbe CLI auf einer anderen Maschine (eine Zeile für Ihre Zwischenablage) und der Server `creds-mcp` für KI-Agenten.",
    why: "Die Erweiterung ist der Tresor; dies sind seine Türen für Terminals und Agenten. Keine davon kann ein Geheimnis halten oder beschaffen — sie reichen Anfragen an das VS-Code-Fenster weiter, dem der Eintrag gehört.",
    setup: "Menü „…“ des Baums → Install…. Jeder Punkt sagt, was er schreibt und wohin; der MCP-Punkt schreibt Ihnen zusätzlich den Konfigurationsblock des Clients.\n\n**Copy install command for another machine…** stellt zwei Fragen — welche Binärdatei (`creds` oder `creds-mcp`) und welche Maschine — und legt eine Bash- oder PowerShell-Zeile in Ihre Zwischenablage. Diese Zeile findet die neueste Veröffentlichung selbst und prüft den Download vor der Installation, hier muss also nichts die Version kennen.",
    usage: "Nach der Installation der CLI öffnen Sie einen Eintrag und führen „Enable CLI Access…“ aus, um einen Namen zu vergeben — danach `creds ssh <name>` aus jedem Terminal. Nach der Installation des MCP-Servers starten Sie Ihren MCP-Client neu und öffnen ihm Einträge über den Abschnitt Agent access.",
    whatCanGoWrong: "„No open window“ von `creds` heißt, dass kein VS-Code-Fenster mit der Erweiterung läuft oder der Zugriff auf den Eintrag nicht freigeschaltet wurde. Innerhalb von WSL wechselt der Aufruf automatisch nach Windows; tut er das nicht, fehlt die Windows-Binärdatei — aus demselben Menü neu installieren.",
  },
  'git-storage': {
    title: "Den Tresor in einem Git-Repository halten",
    whatItIs: "Eine dritte Art von Ort, neben einem Ordner und einem Server: ein privates Git-Remote. Der verschlüsselte Tresor ist eine Datei im Repository, und jede Synchronisation ist ein Pull und ein Push.",
    why: "Vielleicht haben Sie längst einen Ort, der privat, versioniert, gesichert und von überall erreichbar ist — und im Betrieb nichts kostet. Was Sie gegenüber einem Ordner dazubekommen, ist Geschichte: jede Version des Tresors ist ein Commit, eine schlechte Zusammenführung oder ein schlechter Tag ist also mit dem Werkzeug behebbar, das Ihr Team ohnehin kennt.",
    setup: "- Legen Sie ein **privates** Repository an. Leer ist gut; sonst kommt nichts hinein.\n- Am Konto -> **Set Sync Location…**, und geben Sie eine Adresse an, die unverkennbar Git ist: `git@github.com:me/vault.git`, `ssh://…`, oder jede Adresse, die auf `.git` endet. Ein schlichtes `https://github.com/me/vault` gilt absichtlich NICHT als Git — es sieht genau aus wie eine Server-URL.\n- **Die Anmeldung ist eine von zweien.** Über SSH richten Sie `gitDeployKeys` auf einen SSH-Schlüssel-Eintrag, der schon in Ihrem Tresor liegt — `{ \"git@github.com:me/vault.git\": \"<entry id>\" }` — und er wird nur für die Dauer des Aufrufs in eine private Datei geschrieben. Über HTTPS wird ein Token per Credential Helper über stdin geliefert, nie in der URL, wo es im Reflog und in den Protokollen jedes Remotes landen würde.",
    usage: "Danach ist es wie jeder andere Ort, und Git fassen Sie nicht mehr an: eine Synchronisation zieht, führt zusammen, committet und pusht von allein.\n\n- Alles lebt auf einem eigenen Branch, `creds-vault`, ein Repository, das Sie auch für anderes nutzen, wird also nicht gestört.\n- Eine `.gitattributes` markiert `*.enc` als binär, ohne Diff und ohne Merge. Git darf nie versuchen, zwei Geheimtexte Zeile für Zeile in Einklang zu bringen — die Zusammenführung macht die Erweiterung, auf dem entschlüsselten Baum, und erst danach wird wieder verschlüsselt.\n- Das Remote sieht Commits aus Geheimtext. GitHub, Ihre Kolleginnen und jeder, der klont, sehen dasselbe wie Sie: Bytes.",
    whatCanGoWrong: "Ein **öffentliches** Repository ist immer noch Geheimtext und immer noch eine schlechte Idee: es veröffentlicht Ihre Topologie — wie viele Einträge, wie oft Sie arbeiten, wann Sie etwas geändert haben.\n\nKann sich der Schlüssel oder das Token nicht anmelden, hält die Synchronisation an und sagt es. Nichts geht verloren; der Tresor ist lokal und vollständig, bis das Remote wieder antwortet.\n\nCommitten Sie nicht von Hand auf `creds-vault`. Dort schreibt ein Programm, das erwartet, der einzige Schreiber zu sein, und ein handgemachter Commit ist eine Zusammenführung, für die niemand entworfen hat.",
  },
  'basics': {
    title: "Einträge: die neun Arten, und was jede tut",
    whatItIs: "Konten halten Ordner, Ordner halten Einträge. Ein Eintrag ist eine Sache, die Sie benutzen — ein Host, eine Datenbank, ein Schlüssel — und seine Art entscheidet, was die Schaltfläche Connect darauf tatsächlich tut.",
    why: "Ein Passwortmanager speichert; dieser speichert und HANDELT dann. Deshalb zählt die Art: sie ist kein Etikett zum Sortieren, sondern die Handlung, die der Eintrag trägt.",
    setup: "Rechtsklick auf einen Ordner -> **Add Entry**, Art wählen, ausfüllen, was Sie haben. Ein typisierter Ordner entscheidet die Art für Sie. Rechtsklick -> **Edit** ändert später alles, und jeder Eintrag behält seine **letzten 3 Versionen**, eine Änderung ist also keine Einbahnstraße.\n\nZwei Dinge, die Sie sich nie selbst ausdenken müssen: ein **Passwort oder eine Passphrase**, mit einer Schaltfläche im Formular erzeugt, und ein **SSH-Schlüssel**, ebenso erzeugt, in sechs Typen (Ed25519 zuerst und empfohlen, drei ECDSA-Kurven, RSA 3072 und 4096).",
    usage: "**Die neun Arten:**\n\n- **credential** — ein Login, eine URL und ein Passwort. Die schlichte Art, für alles, was einfach ein Konto irgendwo ist.\n- **ssh** — ein Host: Benutzer, Port und entweder ein gespeicherter Schlüssel oder ein Passwort. Connect öffnet ein Terminal darauf.\n- **sshkey** — ein privater Schlüssel, hier erzeugt oder eingefügt. Installieren Sie ihn auf einem Host, oder laden Sie ihn in den Agenten, damit `ssh` und `git` ihn ohne Datei auf der Platte verwenden.\n- **vpn** — eine OpenVPN- oder WireGuard-Konfiguration. Tunnel aus dem Baum starten und stoppen.\n- **db** — eine Verbindung: Typ, Host, Port, Benutzer, Passwort. In Ihrem Datenbank-Client öffnen, oder eine Abfrage ausführen, ohne dass das Passwort je die Kommandozeile erreicht.\n- **terminal** — ein Befehl, den Sie gespeichert haben, mit seinen Argumenten als Zeilen und einer Notiz an jeder. Mit einem Klick ausführen, statt ihn sich zu merken.\n- **script** — ein Skript mit Hervorhebung bearbeitet, dessen `${NAME}`-Variablen als Zeilen herausgezogen und über die Umgebung geliefert statt in den Rumpf geklebt werden.\n- **config** — eine ganze Konfigurationsdatei, die der Tresor aus Git heraushält. Hat einen eigenen Artikel.\n- **payment** — eine Karte, Bankdaten oder eine Seed-Phrase, so zurückgelesen, wie sie gedruckt sind. Ebenfalls mit eigenem Artikel, denn eine Kartennummer ist kein Passwort und will nicht wie eines gezeigt werden.\n\nJeder Eintrag kann außerdem Notizen tragen, eine verschlüsselte Datei, ein Bild, einen Seed für Einmalcodes und eine **Lebensdauer** — eine Stunde, ein Tag, bis VS Code schließt — nach der er wirklich gelöscht und nicht als verbraucht markiert wird.\n\n**In der Zeile selbst:** *View Details* öffnet den Eintrag schreibgeschützt, sodass Sie schauen können, ohne ein Bearbeitungsformular; *Move to Folder…* legt ihn um (und *Move Up* / *Move Down* ordnen von Hand); *Toggle SSH (on/off)* kippt den SSH-Schalter des einzelnen Eintrags, der bei einem neuen Eintrag aus ist; *Save VPN Config As…* schreibt die Konfiguration eines VPN-Eintrags in eine Datei, für einen Client, der darauf besteht.",
    whatCanGoWrong: "Ein typisierter Ordner verweigert eine Art, die er nicht hält; verschieben Sie den Eintrag oder nehmen Sie einen Ordner vom Typ *any*.\n\nEinen Schlüssel zu erzeugen heißt nicht, ihn zu installieren: die öffentliche Hälfte muss noch zum Host gelangen, und genau dafür ist **Install SSH Key** da.",
  },
  'import-existing': {
    title: "Hereinholen, was Sie schon haben",
    whatItIs: "Ihre vorhandenen Hosts und Logins aus `~/.ssh/config` oder aus einem anderen Passwortmanager einlesen, statt sie abzutippen.",
    why: "Ein Tresor, den man von Hand füllen muss, bleibt leer, und halb gefüllt ist schlimmer als beides: sobald zwei Orte Ihre Zugangsdaten halten, wird keinem davon getraut.",
    setup: "Rechtsklick auf ein Konto -> **Import from ~/.ssh/config or another manager…**, und die Datei wählen. Was herüberkommt:\n\n- **`~/.ssh/config`** — Host, HostName, User, Port, IdentityFile, als verbindungsfähige SSH-Einträge.\n- **Bitwarden, KeePass, LastPass, Termius (CSV)** — Name, Benutzername, Passwort, Adresse, Notizen, Einmalcode-Seed, Ordner.\n- **Bitwarden, 1Password (JSON)** — dasselbe, aus Login-Einträgen.\n\n**Import from External…** ist die Gegenrichtung von *Export / Share Externally* — eine versiegelte Datei, die Ihnen jemand geschickt hat.",
    usage: "Der INHALT der Datei entscheidet, wie sie gelesen wird, ein falsch benannter Export lässt sich also trotzdem importieren.\n\nNichts landet, bevor Sie die Anzahl gesehen haben und das, was übersprungen wird — und übersprungene Zeilen werden mit Grund aufgeführt, statt still zu verschwinden. Alles bekommt eine frische Id, ein Import kann also nie überschreiben, was Sie schon hatten.",
    whatCanGoWrong: "**KDBX — die eigene Datenbank von KeePass — wird bewusst nicht gelesen**: sie ist mit Argon2 verschlüsselt, Argon2 gibt es in Node nicht, und eine halb richtige Umsetzung davon wäre schlimmer als gar keine. KeePass exportiert CSV, und das importiert einwandfrei.\n\nEin Import fügt hinzu; er führt nie mit dem Vorhandenen zusammen. Zwei Importe derselben Datei geben Ihnen zwei Kopien, denn eine frische Id ist genau das, was verhindert, dass der erste überschrieben wird.",
  },
  'trash': {
    title: "Der Papierkorb: löschen und zurückholen",
    whatItIs: "Einen Eintrag oder einen Ordner zu löschen verschiebt ihn in den Papierkorb — einen Ordner wie jeder andere, den Sie öffnen, hineinsehen und aus dem Sie herausziehen können. Weg ist es, wenn der Papierkorb geleert wird, und nicht früher.",
    why: "Eine Löschung SYNCHRONISIERT. Löschen Sie auf dem Notebook, stimmt der nächste Abgleich am Desktop zu, dass es weg ist, überall, samt Verlauf. Der Papierkorb ist das Fenster, in dem dieser Fehler noch Ihrer ist.",
    setup: "Rechtsklick -> **Delete**. Um zu entscheiden, wie lange Dinge dort liegen: ⋯ -> **Empty the Trash Automatically…**. Um sofort zu leeren: **Empty the Trash Now**.",
    usage: "- **Restore** legt einen Eintrag dorthin zurück, WOHER er gelöscht wurde, nicht in die Wurzel — und **Go to the Original Folder** zeigt Ihnen vorher, wo das ist.\n- Ordner werden ebenso wiederhergestellt, und der Baum zeigt, was zurückkam.\n- **Nichts im Papierkorb antwortet einem Agenten**, was seine Schalter auch sagen. Ein gelöschtes Ding, das noch funktioniert, machte das Wort bedeutungslos.\n\nEin Eintrag mit Lebensdauer ist die Ausnahme: **Burn Now…** darauf ist eine echte Löschung und keine Verschiebung — das Geheimnis, seine aufbewahrten Versionen und, per Grabstein, jede synchronisierte Kopie. Der Dialog sagt das, bevor Sie zustimmen.",
    whatCanGoWrong: "Leeren ist endgültig und es synchronisiert: hinter dem ersten Papierkorb gibt es keinen zweiten.\n\nEin Eintrag, der wiederhergestellt wird, nachdem sein ursprünglicher Ordner selbst gelöscht wurde, landet in der Wurzel — den Ort, von dem er kam, gibt es nicht mehr.",
  },
  'project-folders': {
    title: "Projektordner: der ganze Satz mit einem Klick",
    whatItIs: "Ein Ordner vom Typ **project** ist ein Behälter für ein Stück Arbeit, und ihn anzulegen stellt den typisierten Satz sofort darin auf: Datenbanken, VPNs, SSH-Schlüssel, SSH-Verbindungen, Passwörter, Terminalbefehle und Skripte.",
    why: "Was ein Projekt braucht, ist selten von einer Art. Jedes Mal sieben Ordner von Hand anzulegen ist die Sorte Pflicht, die Leute auslassen, und ein Tresor, in dem Ähnliches in verschiedenen Formen liegt, ist ein Tresor, in dem niemand etwas findet.",
    setup: "Rechtsklick auf ein Konto oder einen Ordner -> **Add Folder**, und den Typ auf **project** setzen. Der Satz erscheint sofort darin. **Change Folder Type…** wandelt einen vorhandenen Ordner um.",
    usage: "Der Typ ist es, der den Baum vorhersagbar macht: ein typisierter Unterordner entscheidet die Art der Einträge, die Sie hineinlegen, *Add Entry* in `db` gibt Ihnen also eine Datenbank und keine Frage.\n\n`project` selbst schreibt über Einträge nichts vor — es ist ein reiner Ordnertyp, und seine eigenen Einträge auf eine Art namens „project“ zu zwingen hieße, eine Entitätsart zu erfinden, die es nicht gibt. Die Bedeutung trägt die Form dessen, was er aufstellt.\n\nAgentenzugriff, der auf einem Projektordner gesetzt wird, vererbt sich auf alles darunter, und genau das macht ihn zur natürlichen Einheit, die man einem Agenten öffnet: ein Schalter, ein Projekt.",
    whatCanGoWrong: "Die aufgestellten Ordner sind gewöhnliche Ordner. Löschen Sie die, die Sie nicht brauchen — nichts hängt davon ab, dass alle sieben existieren.",
  },
};
