import { HelpBody } from './helpContent';

/**
 * Spanish bodies, one entry per article id.
 *
 * <p>Written against the English article rather than word for word: the catalog's shape is what
 * carries — what it is, why, how to set it up, how to use it, what can go wrong — and a sentence
 * that reads as a translation reads as a translation. Command names, setting keys and menu entries
 * stay in English, because that is what the person sees on screen.</p>
 *
 * <p>An article missing from this map falls back to English VISIBLY, which is the rule the catalog
 * has always had: a missing translation must never hide an article.</p>
 */
export const ES_BODIES: Readonly<Record<string, HelpBody>> = {
  'getting-started': {
    title: "Empiece aquí: una cuenta y el lugar donde vive su caja fuerte",
    whatItIs: "Una cuenta es una caja fuerte: su propio árbol, su propio cifrado, su propio sitio donde vivir. Crearla es lo primero que hace usted — carpetas, entradas y todo lo demás cuelgan de ella.\n\nUna caja fuerte funciona por completo sin ningún sitio. Lo que añade una ubicación es una segunda máquina y otras personas.",
    why: "Todo se cifra en su máquina antes de salir de ella, así que la ubicación solo guarda texto cifrado — aun así conviene elegirla al principio y no más tarde, cuando varias máquinas ya tienen copias de la anterior.",
    setup: "Fila de la cuenta -> **Add Account**, e inicie sesión. Después, en esa cuenta -> **Set Sync Location…**, y elija una de dos:\n\n- una **carpeta** — cualquier ruta en la que esta máquina pueda escribir: `Z:\\\\Backups`, `\\\\\\\\NAS\\\\Vault`, `/mnt/nas/vault`, o una carpeta que ya sincronice otra cosa;\n- un **servidor** — la URL de un Cred Vault Server, `https://vault.company.com`.\n\nDéjelo vacío y la caja fuerte se queda en esta máquina: todo funciona, nada se sincroniza. Un repositorio git es una tercera opción y tiene su propio artículo.",
    usage: "**Cuál de las dos, y no es cuestión de gusto:**\n\n- Una **carpeta** cuando es usted solo, o unas pocas personas que ya comparten almacenamiento. Nada que ejecutar y nada que mantener. El remitente de una entrada compartida se acepta por confianza en el primer contacto: usted lee la huella en voz alta una vez y la recuerda.\n- Un **servidor** cuando hay más de una persona. Sella el remitente de una compartición a partir de un inicio de sesión verificado, de modo que no se puede falsificar; limita las lecturas a su propio token; y las altas y bajas siguen al proveedor de identidad que ya tiene.\n\nNinguno de los dos puede leer nada. Lo que viaja y lo que se guarda es texto cifrado en ambos casos, y el servidor no tiene clave ni ninguna ruta de código por la que pudiera conseguirla.",
    whatCanGoWrong: "Sin ubicación no hay nada roto — la caja fuerte es local y está completa. Lo que no tiene es una segunda máquina ni compartición.\n\nCambiar la ubicación más tarde no mueve el archivo antiguo. Apunte la nueva a la misma carpeta, o sincronice una vez desde la máquina que todavía tiene los datos.\n\n**Sign Out / Remove Account** quita la cuenta de ESTA máquina — el árbol, su archivo de caja fuerte y sus claves aquí. No es un borrado en el servidor ni en la carpeta de sincronización: vuelva a iniciar sesión, o añada la cuenta en otra máquina, y el árbol regresa. **Reset Google OAuth** es el martillo pequeño para un inicio de sesión que salió mal: olvida el client secret guardado y todas las sesiones de Google, deja las cajas fuertes en paz, y el siguiente inicio empieza limpio.\n\nEn una cuenta de servidor, **Server Metrics…** lee el único documento JSON que el servidor publica sobre sí mismo. Quien no esté en la lista de oficiales recibe la negativa del propio servidor, con palabras.\n\nUna ubicación que parece una dirección git — `git@…`, `ssh://…`, o un sufijo `.git` — se convierte en una caja fuerte git y no en una carpeta. Es deliberado, y por eso un simple `https://github.com/me/vault` NO se adivina: podría ser igual de bien la URL de un servidor.",
  },
  'protection': {
    title: "Cerrar la caja fuerte: el PIN, una llave de seguridad, el bloqueo automático",
    whatItIs: "Tres maneras independientes de entrar y un temporizador que decide cuánto permanece abierta una caja fuerte desbloqueada: un **PIN de sincronización**, una o varias **llaves de seguridad** (YubiKey / FIDO2) y un **código de recuperación** impreso.",
    why: "Una caja fuerte cifra su contenido con una clave maestra aleatoria, y esa clave se envuelve una vez por cada método de entrada — una envoltura para el PIN, una por cada llave registrada. Cualquier envoltura abre la caja, y por eso añadir o quitar una llave nunca vuelve a cifrar sus datos ni invalida las demás.",
    setup: "- **Set Sync PIN** — el mismo PIN en cada máquina que sincronice esta cuenta. Sin él, otra máquina descarga un archivo que no puede abrir.\n- **Add Security Key (YubiKey)…** en la fila de la cuenta. El sistema operativo muestra su propio diálogo de llave de seguridad, y el secreto PRF de WebAuthn de la llave se convierte en clave de envoltura. Registre tantas como quiera.\n- **Set Auto-Lock…** — minutos de inactividad SUYA. 60 por defecto; `0` no bloquea nunca.\n- **Set Up Recovery Code…** — la tercera vía de entrada, en papel. Tiene su propio artículo, y conviene hacerlo antes de necesitarlo.",
    usage: "Desbloquear con una llave es un toque, al estilo de un inicio de sesión de Microsoft: ninguna contraseña escrita. La clave maestra se retiene después durante la ventana, así que la sincronización en segundo plano no vuelve a preguntar. **Lock Vaults** la descarta; **Unlock Vault (Security Key)…** pregunta cuando usted quiera.\n\nEl bloqueo automático cuenta SUS acciones — abrir o copiar unas credenciales, conectar, instalar una clave, editar, desbloquear. No el movimiento del ratón, y deliberadamente no la sincronización en segundo plano: un temporizador de cinco minutos contado como actividad significaría que la ventana de inactividad no se cumple nunca y que el ajuste no hace nada en silencio.\n\nBloquear olvida la clave maestra. Las credenciales locales siguen funcionando, porque viven en el llavero del sistema operativo y no están protegidas por la clave de la caja fuerte.",
    whatCanGoWrong: "Sin PIN la caja fuerte es local en la práctica: otra máquina puede descargar el archivo y no abrirlo.\n\nQuitar su última llave de seguridad cuando ha olvidado el PIN deja el código de recuperación y nada más — que es el argumento para imprimirlo pronto.\n\n`autoLockMinutes: 0` no bloquea nunca. Es una opción que alguien puede querer, no un valor por defecto.",
  },
  'recovery-code': {
    title: "El código de recuperación impreso",
    whatItIs: "Un código de 150 bits mostrado una sola vez, impreso, guardado en papel — la tercera vía de entrada a la caja fuerte para el día en que el PIN se ha olvidado Y la llave de seguridad no está.",
    why: "Los dos factores cotidianos pueden fallar a la vez: un PIN olvidado y un YubiKey perdido son una mala semana, no una paradoja.",
    setup: "«Set Up Recovery Code…» lo muestra una vez, con Print y deliberadamente sin Copy: los portapapeles los leen gestores, herramientas de sincronización y tuberías de capturas de pantalla, y este factor tiene que sobrevivir al portátil.",
    usage: "«Unlock Vault (Recovery Code)…», tecléelo desde el papel — una errata la nombra la suma de verificación en local — y después fije un PIN nuevo.",
    whatCanGoWrong: "Generar un código nuevo retira la impresión anterior. Quitar su última llave de seguridad puede retirar también el código (volver a envolver necesita el código, y el código está en papel) — la extensión ya lo dice en voz alta.",
  },
  'backup': {
    title: "Instantáneas: copias fechadas que nunca se fusionan",
    whatItIs: "Copias fechadas de la caja fuerte, escritas en un almacenamiento propio según el calendario que usted elija. No es lo mismo que la sincronización, y es deliberado.",
    why: "La sincronización mantiene una caja fuerte viva y FUSIONA — lo que significa que un borrado se propaga. Borre unas credenciales en el portátil y la siguiente sincronización del escritorio coincide en que ya no están. Eso es correcto para una caja viva e inútil como red de seguridad, así que las instantáneas son una segunda vía independiente que nunca fusiona y nunca borra en nombre de nadie.",
    setup: "- **Dónde** — `backupLocation`, o por cuenta -> **Set Backup Location…**. Una carpeta en un NAS, un disco externo, **una carpeta de sincronización de Google Drive o OneDrive** — cualquier sitio donde esta máquina pueda escribir. Vacío desactiva las instantáneas.\n- **Cuándo** — `backupIntervalHours`: 24 a diario, 168 semanal, `0` apagado. Por cuenta -> **Set Backup Schedule…**. **Snapshot Vault Now** toma una de inmediato.\n- **Cuánto tiempo** — `backupRetainDays`, 30 por defecto; `0` lo guarda todo.",
    usage: "**Las instantáneas funcionan aunque la caja fuerte viva en un servidor**, y son a propósito dos ajustes separados que apuntan a almacenamientos separados: un servidor es el servicio de alguien, y una instantánea es su propia copia de sus propios datos.\n\nApuntar las instantáneas a una carpeta sincronizada con la nube le da historial fuera de la máquina sin dar a nadie el texto en claro: una instantánea tiene el mismo formato cifrado que todo lo demás y se abre con la cuenta y el PIN.\n\nUna instantánea idéntica a la anterior no se escribe, así que una caja fuerte tranquila no llena de copias de sí misma una carpeta que se paga por uso. La más reciente no se borra nunca, tenga la edad que tenga: un portátil cerrado durante un año no debe volver a una carpeta de copias vacía.",
    whatCanGoWrong: "Apuntar las instantáneas al MISMO sitio que la caja fuerte las anula — la red de seguridad y aquello que debe recoger compartirían un solo fallo.\n\nLas instantáneas llevan adjuntos, imágenes y configuraciones de VPN además de contraseñas, así que la carpeta crece con ellas. La retención es lo que la mantiene acotada.",
  },
  'restore': {
    title: "Restaurar desde una instantánea",
    whatItIs: "Leer una copia fechada de vuelta a su cuenta, desde el menú ⋯ del árbol -> **Import / Restore**.",
    why: "La otra mitad de la red de seguridad. Una instantánea que nadie puede restaurar es una carpeta de archivos, y el momento de descubrir que no se abre no es el momento en que la necesita.",
    setup: "⋯ -> **Import / Restore**, elija el archivo `.enc` y responda a lo que le pregunte. CUÁL pregunta recibe es una propiedad del archivo, no del comando:\n\n- una instantánea con ranuras de clave se abre por la puerta propia de la caja fuerte — un toque de la llave de seguridad o el PIN, la misma puerta que usa la sincronización;\n- una copia autónoma con solo una ranura de PIN pide el **PIN de copia que se fijó al crearla**, y un toque de llave no la abre. El diálogo lo dice, porque de otro modo el silencio se leería como que se está ignorando la llave.",
    usage: "**Restaurar SUSTITUYE el árbol de esa cuenta por el de la instantánea.** No es una fusión: las entradas que la instantánea no contiene desaparecen junto con sus secretos. Eso es lo que la convierte en una restauración y no en una importación — y por eso el ensayo seguro se hace en una cuenta desechable y no en la que usted usa.\n\nUna instantánea lo lleva todo: adjuntos, imágenes, configuraciones de VPN, notas e historial de versiones, no solo contraseñas.",
    whatCanGoWrong: "Una instantánea escrita por una compilación más nueva se niega a abrirse en una más antigua — *Unsupported backup version*. Actualice la extensión y después restaure.\n\nSi la cuenta tiene una ubicación de sincronización, restaurar una instantánea antigua y sincronizar después propaga ese estado antiguo a sus otras máquinas. Decida qué copia es la verdad antes de que corra la siguiente sincronización.",
  },
  'sync-vs-snapshots': {
    title: "La sincronización y las instantáneas son máquinas distintas",
    whatItIs: "La sincronización fusiona un archivo cifrado por perfil entre máquinas (de forma causal: dos máquinas que editan a la vez convergen). Las instantáneas son copias fechadas que nunca se fusionan.",
    why: "Una fusión propaga un borrado — ese es su trabajo. La instantánea es la copia que todavía tiene lo que usted borró.",
    setup: "Set Sync Location… por cuenta (carpeta, URL de servidor o un repositorio git). Apunte backupLocation a un almacenamiento DISTINTO. El mismo Sync PIN en todas las máquinas.",
    usage: "Sync Now, o autoSync. Snapshot Vault Now para un punto manual; Import / Restore para volver.",
    whatCanGoWrong: "Sincronización e instantáneas en la misma carpeta anulan la razón de que sean dos. Una restauración devuelve la caja fuerte tal como estaba ENTONCES — sincronizar después vuelve a incorporar las ediciones más nuevas.",
  },
  'install-menu': {
    title: "Install… — qué instala y dónde",
    whatItIs: "Un submenú, tres instaladores: la CLI de terminal `creds` en esta máquina, la misma CLI en otra máquina (una línea de comando para su portapapeles) y el servidor `creds-mcp` para agentes de IA.",
    why: "La extensión es la caja fuerte; estos son sus puertas para terminales y agentes. Ninguno puede guardar ni obtener un secreto: retransmiten peticiones a la ventana de VS Code que posee la entrada.",
    setup: "Menú «…» del árbol → Install…. Cada elemento dice qué escribe y dónde; el de MCP además le escribe el bloque de configuración del cliente.\n\n**Copy install command for another machine…** hace dos preguntas — qué binario (`creds` o `creds-mcp`) y qué máquina — y deja una línea de bash o de PowerShell en su portapapeles. Esa línea encuentra sola la versión más reciente y comprueba la descarga antes de instalar, así que nada de aquí tiene que conocer la versión.",
    usage: "Después de instalar la CLI, abra una entrada y ejecute «Enable CLI Access…» para acuñar un nombre — y luego `creds ssh <name>` desde cualquier terminal. Después de instalar el servidor MCP, reinicie su cliente MCP y ábrale entradas desde la sección Agent access.",
    whatCanGoWrong: "«No open window» de `creds` significa que no hay ninguna ventana de VS Code con la extensión en marcha, o que el acceso de la entrada no se habilitó. Dentro de WSL la llamada cruza a Windows automáticamente; si no lo hace, falta el binario de Windows — reinstálelo desde el mismo menú.",
  },
  'git-storage': {
    title: "Guardar la caja fuerte en un repositorio git",
    whatItIs: "Un tercer tipo de ubicación, junto a una carpeta y un servidor: un remoto git privado. La caja fuerte cifrada es un archivo del repositorio, y cada sincronización es un pull y un push.",
    why: "Puede que ya tenga un sitio privado, versionado, respaldado y accesible desde todas partes — y que no cueste nada mantener. Lo que gana frente a una carpeta es historia: cada versión de la caja fuerte es un commit, así que una fusión mala o un mal día se recuperan con la herramienta que su equipo ya conoce.",
    setup: "- Cree un repositorio **privado**. Vacío está bien; ahí no va nada más.\n- En la cuenta -> **Set Sync Location…**, y dé una dirección que sea inequívocamente git: `git@github.com:me/vault.git`, `ssh://…`, o cualquier dirección terminada en `.git`. Un simple `https://github.com/me/vault` NO se toma como git, deliberadamente: se parece exactamente a la URL de un servidor.\n- **La autenticación es una de dos.** Por SSH, apunte `gitDeployKeys` a una entrada de clave SSH que ya esté en su caja fuerte — `{ \"git@github.com:me/vault.git\": \"<entry id>\" }` — y se escribe en un archivo privado solo durante la llamada. Por HTTPS un token se entrega por un credential helper a través de stdin, nunca en la URL, donde acabaría en el reflog y en los registros de todos los remotos.",
    usage: "A partir de ahí es igual que cualquier otra ubicación y usted no vuelve a tocar git: una sincronización hace pull, fusiona, hace commit y push por su cuenta.\n\n- Todo vive en una rama propia, `creds-vault`, así que un repositorio que además use para otra cosa no se ve alterado.\n- Un `.gitattributes` marca `*.enc` como binario, sin diff y sin merge. Git no debe intentar nunca reconciliar dos textos cifrados línea a línea: la fusión la hace la extensión, sobre el árbol descifrado, y solo después se vuelve a cifrar.\n- El remoto ve commits de texto cifrado. GitHub, sus compañeros y cualquiera que lo clone ven lo mismo que vería usted: bytes.",
    whatCanGoWrong: "Un repositorio **público** sigue siendo texto cifrado y sigue siendo mala idea: publica su topología — cuántas entradas, con qué frecuencia trabaja, cuándo cambió algo.\n\nSi la clave o el token no se autentican, la sincronización se detiene y lo dice. No se pierde nada; la caja fuerte es local y completa hasta que el remoto vuelva a responder.\n\nNo haga commits a mano en `creds-vault`. Ahí escribe un programa que espera ser el único que escribe, y un commit hecho a mano es una fusión que nadie diseñó.",
  },
  'basics': {
    title: "Entradas: los nueve tipos, y qué hace cada uno",
    whatItIs: "Las cuentas contienen carpetas; las carpetas contienen entradas. Una entrada es una cosa que usted usa — un host, una base de datos, una clave — y su tipo decide qué hace realmente el botón Connect que lleva.",
    why: "Un gestor de contraseñas guarda; este guarda y luego ACTÚA. Por eso importa el tipo: no es una etiqueta para ordenar, es qué acción lleva la entrada.",
    setup: "Clic derecho en una carpeta -> **Add Entry**, elija el tipo, rellene lo que tenga. Una carpeta con tipo decide el tipo por usted. Clic derecho -> **Edit** cambia cualquier cosa después, y cada entrada guarda sus **últimas 3 versiones**, así que editar no es una puerta de un solo sentido.\n\nDos cosas que nunca tiene que inventarse: una **contraseña o frase de paso**, generada con un botón del formulario, y una **clave SSH**, generada igual en seis tipos (Ed25519 primero y recomendado, tres curvas ECDSA, RSA 3072 y 4096).",
    usage: "**Los nueve tipos:**\n\n- **credential** — un usuario, una URL y una contraseña. El sencillo, para todo lo que es simplemente una cuenta en algún sitio.\n- **ssh** — un host: usuario, puerto y o bien una clave guardada o bien una contraseña. Connect abre un terminal en él.\n- **sshkey** — una clave privada, generada aquí o pegada. Instálela en un host, o cárguela en el agente para que `ssh` y `git` la usen sin ningún archivo en disco.\n- **vpn** — una configuración de OpenVPN o WireGuard. Levante y baje el túnel desde el árbol.\n- **db** — una conexión: tipo, host, puerto, usuario, contraseña. Ábrala en su cliente de base de datos, o ejecute una consulta sin que la contraseña llegue nunca a la línea de comandos.\n- **terminal** — un comando que guardó, con sus argumentos como filas y una nota en cada uno. Ejecútelo con un clic en lugar de recordarlo.\n- **script** — un script editado con resaltado, cuyas variables `${NAME}` se extraen como filas y se entregan por el entorno en vez de pegarse en el cuerpo.\n- **config** — un archivo de configuración entero que la caja fuerte mantiene fuera de git. Tiene su propio artículo.\n- **payment** — una tarjeta, datos bancarios o una frase semilla, leídos como están impresos. También con su propio artículo: un número de tarjeta no es una contraseña y no quiere que se lo muestre como tal.\n\nCualquier entrada puede además llevar notas, un archivo cifrado, una imagen, una semilla de códigos de un solo uso y una **vida útil** — una hora, un día, hasta que VS Code se cierre — tras la cual se borra de verdad en lugar de marcarse como gastada.\n\n**En la fila misma:** *View Details* abre la entrada en solo lectura, para mirar sin un formulario de edición; *Move to Folder…* la reubica (y *Move Up* / *Move Down* la ordenan a mano); *Toggle SSH (on/off)* cambia el interruptor SSH de esa entrada, que en una nueva está apagado; *Save VPN Config As…* escribe la configuración de una entrada vpn a un archivo, para un cliente que insista en tenerlo.",
    whatCanGoWrong: "Una carpeta con tipo rechaza un tipo que no contiene; mueva la entrada o use una carpeta de tipo *any*.\n\nGenerar una clave no es instalarla: la mitad pública todavía tiene que llegar al host, y para eso está **Install SSH Key**.",
  },
  'import-existing': {
    title: "Traer lo que ya tiene",
    whatItIs: "Leer sus hosts y accesos existentes desde `~/.ssh/config` o desde otro gestor de contraseñas, en lugar de volver a teclearlos.",
    why: "Una caja fuerte que hay que llenar a mano se queda vacía, y medio llena es peor que cualquiera de las dos cosas: en cuanto dos sitios guardan sus credenciales, no se confía en ninguno.",
    setup: "Clic derecho en una cuenta -> **Import from ~/.ssh/config or another manager…**, y elija el archivo. Lo que cruza:\n\n- **`~/.ssh/config`** — Host, HostName, User, Port, IdentityFile, como entradas SSH conectables.\n- **Bitwarden, KeePass, LastPass, Termius (CSV)** — nombre, usuario, contraseña, dirección, notas, semilla de código de un solo uso, carpeta.\n- **Bitwarden, 1Password (JSON)** — lo mismo, desde los elementos de acceso.\n\n**Import from External…** es la dirección contraria de *Export / Share Externally*: un archivo sellado que alguien le envió.",
    usage: "Es el CONTENIDO del archivo lo que decide cómo se lee, así que una exportación con el nombre cambiado se importa igual.\n\nNada aterriza antes de que usted haya visto el recuento y lo que se va a omitir — y las filas omitidas se enumeran con su motivo en lugar de caer en silencio. Todo recibe un identificador nuevo, así que una importación nunca puede sobrescribir lo que ya tenía.",
    whatCanGoWrong: "**KDBX — la base de datos propia de KeePass — no se lee**, deliberadamente: está cifrada con Argon2, Argon2 no está en Node, y una implementación a medias de eso sería peor que ninguna. KeePass exporta CSV, y eso se importa sin problema.\n\nUna importación añade; nunca fusiona con lo que hay. Dos importaciones del mismo archivo le dan dos copias, porque un identificador nuevo es precisamente lo que impide que se sobrescriba la primera.",
  },
  'trash': {
    title: "La Papelera: borrar y recuperar",
    whatItIs: "Borrar una entrada o una carpeta la mueve a la Papelera — una carpeta como cualquier otra, que puede abrir, mirar por dentro y de la que puede sacar cosas. Desaparece cuando la Papelera se vacía, y no antes.",
    why: "Un borrado se SINCRONIZA. Borre en el portátil y la siguiente sincronización del escritorio coincide en que ya no está, en todas partes, junto con su historial. La Papelera es la ventana en la que ese error todavía es suyo para deshacerlo.",
    setup: "Clic derecho -> **Delete**. Para decidir cuánto tiempo quedan las cosas allí: ⋯ -> **Empty the Trash Automatically…**. Para vaciarla ya: **Empty the Trash Now**.",
    usage: "- **Restore** devuelve una entrada al sitio DE DONDE se borró, no a la raíz — y **Go to the Original Folder** le enseña dónde es antes de que se comprometa.\n- Las carpetas también se restauran, y el árbol muestra lo que ha vuelto.\n- **Nada en la Papelera responde a un agente**, digan lo que digan sus interruptores. Una cosa borrada que siguiera funcionando dejaría la palabra sin sentido.\n\nUna entrada con vida útil es la excepción: **Burn Now…** sobre ella es un borrado real y no un movimiento — el secreto, sus versiones guardadas y, por lápida, cada copia sincronizada. El diálogo lo dice antes de que usted acepte.",
    whatCanGoWrong: "Vaciar es permanente y se sincroniza: no hay una segunda Papelera detrás de la primera.\n\nUna entrada restaurada después de que su carpeta original fuera borrada también aterriza en la raíz — el sitio del que venía ya no existe.",
  },
  'project-folders': {
    title: "Carpetas de proyecto: el conjunto entero con un clic",
    whatItIs: "Una carpeta de tipo **project** es un contenedor para un trabajo concreto, y crearla levanta dentro de sí, de golpe, el conjunto con tipos: bases de datos, VPN, claves SSH, conexiones SSH, contraseñas, comandos de terminal, scripts, archivos de configuración y datos de pago.",
    why: "Lo que necesita un proyecto rara vez es de un solo tipo. Hacer nueve carpetas a mano cada vez es la clase de tarea que la gente se salta, y una caja fuerte donde cosas parecidas viven con formas distintas es una caja donde nadie encuentra nada.",
    setup: "Clic derecho en una cuenta o una carpeta -> **Add Folder**, y ponga su tipo en **project**. El conjunto aparece dentro de inmediato. **Change Folder Type…** convierte una carpeta existente.",
    usage: "El tipo es lo que hace el árbol predecible: una subcarpeta con tipo decide el tipo de las entradas que usted añade, así que *Add Entry* en `db` le da una base de datos y no una pregunta.\n\n`project` en sí no dicta nada sobre las entradas — es un tipo solo de carpeta, y forzar sus propias entradas a un tipo llamado «project» sería inventar una clase de entidad que no existe. El significado lo lleva la forma de lo que levanta.\n\nEl acceso de agentes puesto en una carpeta de proyecto lo hereda todo lo que hay debajo, y eso la convierte en la unidad natural que se abre a un agente: un interruptor, un proyecto.",
    whatCanGoWrong: "Las carpetas levantadas son carpetas corrientes. Borre las que no necesite — nada depende de que existan las nueve.",
  },
  'share-with-agent': {
    title: "Share with Claude Code",
    whatItIs: "Darle a un agente de IA el USO de una credencial sin darle la credencial. Clic derecho en una entrada -> **Share with Claude Code…**: se acuña un token de capacidad y en su portapapeles queda un fragmento listo para pegar.",
    why: "Pegar una contraseña en un chat deja el texto en claro en una transcripción y en todos los registros aguas abajo; exportarla a un archivo no es mejor. El agente le pide a la ventana que actúe, la ventana actúa, y sólo vuelve el resultado — no hay en el protocolo ningún campo por el que un secreto pudiera viajar.",
    setup: "Clic derecho en cualquier entrada con la que un agente pueda HACER algo — hosts SSH, scripts, comandos de terminal, bases de datos, túneles VPN, credenciales corrientes -> **Share with Claude Code…**, y entréguele al agente lo que hay en su portapapeles.\n\nEl token nombra UNA entrada y muere con la ventana de VS Code que lo acuñó. El primer uso le pide un clic.\n\nDos límites acortan aún más esa vida, y ambos son ajustes que usted puede cambiar: `agentGrantIdleMinutes` caduca un token que queda sin usar — uno con el que un agente trabaja activamente se renueva solo — y `agentGrantMaxCalls` limita cuántas llamadas puede hacer un token en total, que es el techo que conviene poner cuando entrega un token para un trabajo concreto.",
    usage: "Lo que el agente puede pedir a partir de ahí, un verbo cada uno: ejecutar un comando en el host, abrir la terminal interactiva **para usted**, ejecutar una consulta, ejecutar su script o su comando guardado, exportar el secreto a las terminales nuevas, levantar un VPN.\n\n**Dos de ellos ignoran deliberadamente lo que el agente envía.** `script` y `run` ejecutan exactamente lo que usted guardó, así que ningún texto escrito por el agente llega nunca a una shell ni a un intérprete. Además exigen que usted haya ejecutado la entrada por su cuenta al menos una vez en esta máquina: un Allow cubre un token, no un cuerpo, y una sincronización puede sustituir ese cuerpo después de que usted hizo clic.\n\nEsto no es lo mismo que MCP. Un share es una entrada, un token, esta ventana; MCP es una superficie permanente con interruptores por entrada. Ambos levantan la misma ventana de consentimiento, y ambos figuran en **MCP logs**.",
    whatCanGoWrong: "El token está atado a la ventana que lo acuñó: si la recarga, al agente se le dice que pida uno nuevo. Ésa es la vida prevista, no una avería.\n\nEl agente tiene que poder alcanzar el loopback de esta máquina. Uno que corre dentro de un contenedor no puede, así que para esta función ejecútelo en el cliente.\n\nMongoDB se rechaza a propósito: `mongosh` no tiene variable de entorno para la contraseña, y su `--eval` corre en el mismo intérprete que puede leer el entorno — una «consulta» podría imprimir la credencial de vuelta.",
  },
  'agents-mcp': {
    title: "Agentes por MCP — las dos escaleras",
    whatItIs: "Dos escaleras, diez interruptores. Sobre las ENTRADAS: verla, usarla, reemplazar su secreto, crear entradas, borrar lo que creó, borrar cualquier cosa. Sobre las CARPETAS: crear, renombrar y mover, borrar lo que creó, borrar cualquiera. Todos apagados por defecto, y heredados por todo lo que cuelga de la carpeta donde los pone.",
    why: "Un agente debe alcanzar exactamente lo que usted abrió, nada más — y «abierto» debe verse en la entrada misma, no enterrado en un archivo de configuración.",
    setup: "Edit de una entrada → sección Agent access (MCP), o ponga los interruptores en una carpeta y deje que las entradas los hereden. El servidor se instala desde Install… → Install the MCP Server.",
    usage: "El árbol marca una entrada abierta con un pentágono — cada arista encendida es un interruptor de la escalera de entradas. La rotación pasa por un marcador `{{creds:new}}`, así que ningún valor entra jamás en el contexto del agente. Un agente también puede decir cómo debe SER el secreto generado — longitud, qué conjuntos de caracteres, cuántas palabras —, lo que importa cuando el otro extremo limita la longitud o prohíbe los símbolos; la ventana le muestra lo que pidió. Las carpetas las ve por `creds_folders` y las cambia con `creds_create_folder` / `creds_edit_folder` / `creds_delete_folder`. Toda acción sigue levantando la ventana de consentimiento.\n\nEjecute lo que ejecute el agente, la respuesta se enmascara de salida: un único punto de paso sustituye los valores guardados de esa entrada en el cuerpo de la respuesta antes de que salga de la ventana, y la línea de auditoría dice cuántos atrapó. Así que un comando que devuelve su contraseña por pantalla le entrega al agente una máscara, no la contraseña.",
    whatCanGoWrong: "El interruptor es permiso para PEDIR, no consentimiento: si la ventana le sorprende, es que funciona. Nada en la Papelera responde a los agentes, digan lo que digan sus interruptores. Que un agente vea una lista vacía significa que no hay ningún interruptor encendido. **Un agente nunca puede cambiar un interruptor**: ninguna petición que pueda componer lleva ese campo, así que editar una carpeta es el nombre, el sitio y el tipo y nada más. Mover exige el permiso en los dos extremos, porque una carpeta pasa sus respuestas a todo lo que contiene.",
  },
  'agent-surface': {
    title: "Qué puede y qué no puede un agente",
    whatItIs: "El mapa de la superficie para agentes de esta caja fuerte, tomado del código y no de la memoria: 9 tipos de entrada, 16 herramientas MCP, 10 interruptores de acceso, más de 100 comandos en la extensión.\n\nVale la pena distinguir tres estados. **Explícito** — hay una herramienta para ello. **Implícito** — el agente lo obtiene como consecuencia de otra llamada, sin herramienta propia. **Ninguno** — no se alcanza en absoluto.",
    why: "**La asimetría que conviene saber primero:** un agente puede CREAR una entrada y BORRARLA, y puede reemplazar su secreto — pero no puede EDITAR ningún campo corriente: ni el nombre, ni el host, ni el usuario, ni el puerto. Las carpetas tienen el juego completo desde 0.85.0: crear, renombrar, mover, borrar.\n\nDe modo que un agente que aprovisiona infraestructura puede levantar un árbol de carpetas y llenarlo, y no puede corregir una errata que él mismo cometió — sólo borrar y volver a crear, perdiendo el historial de versiones.",
    setup: "Para el mapa en sí no hay nada que configurar. Lo que un agente alcanza de verdad lo deciden los interruptores de una entrada o de una carpeta — vea el artículo sobre agentes por MCP, que explica las dos escaleras y cómo se heredan.",
    usage: "**Explícito — herramienta propia:**\n\n- creds_list — entradas: nombre, tipo, carpeta, host, puerto, usuario, tipo de base, una cadena de conexión con la contraseña quitada, dependencias. hasPassword, hasPrivateKey, hasNotes y hasTotp dicen que algo existe, nunca qué es.\n- creds_folders — carpetas: id, nombre, padre, tipo, y qué puede hacerse con cada una.\n- creds_exec, creds_query, creds_run, creds_open_terminal, creds_vpn_up, creds_vpn_down — usar una credencial sin recibirla jamás.\n- creds_rotate — reemplazar un secreto mediante un marcador {{creds:new}}. **Sólo para entradas db y ssh**; credential, vpn, terminal, script, config, payment y sshkey no pueden rotarse.\n- creds_create, creds_delete — y desde 0.86.0 la forma del secreto generado: longitud, conjuntos de caracteres, número de palabras.\n- creds_create_folder, creds_edit_folder, creds_delete_folder — carpetas, desde 0.85.0.\n- creds_config_snippet — cómo lee el código una entrada config. Texto público; el contenido de la configuración no se devuelve nunca.\n\n**Implícito — lo que una llamada concede más allá de su nombre:**\n\n- creds_exec es una shell completa en ese host con los derechos de ese usuario: instalar paquetes, leer archivos, red saliente. Es el permiso más ancho del conjunto.\n- creds_query es SQL arbitrario: cualquier tabla, DDL y privilegios dentro de la propia base.\n- creds_run ejecuta código que escribió otra persona — ella lo guardó, el agente elige cuándo.\n- creds_rotate escribe en el historial de versiones: el valor viejo queda allí, el nuevo en la caja fuerte.\n- creds_create con un secreto explícito es el único camino por el que un secreto entra EN la caja fuerte DESDE un agente. El diario cuenta esas líneas aparte.\n- Crear en una carpeta con tipo: el tipo lo dicta la carpeta, no el agente.\n- Mover una carpeta cambia los permisos de todo lo que hay dentro, y por eso el permiso hace falta en los dos extremos.\n- Borrar arranca el reloj de la Papelera. «Reversible» vale hasta que se vacía; para una entrada con vida útil, el borrado es definitivo al instante.\n- creds_export_env cambia lo que verá la próxima terminal de la persona.",
    whatCanGoWrong: "**Con qué se topa un agente y qué no puede hacer:**\n\n- Editar los campos de una entrada — nombre, host, usuario, puerto, notas. Sólo borrar y volver a crear.\n- Rotar algo que no sea una entrada db o ssh.\n- Leer un secreto, una nota, una configuración de VPN o una semilla de códigos de un solo uso — estructuralmente no hay campo por el que pudieran viajar.\n- Usar un código de un solo uso. creds_list dice que hasTotp es cierto y no hay herramienta, así que un agente que está terminando un inicio de sesión se detiene exactamente aquí.\n- Restaurar desde la Papelera. Puede borrar y no puede deshacer.\n- Poner una vida útil a lo que crea.\n- Generar un par de claves SSH. La extensión hace seis tipos en el formulario de la entrada; a un agente se le rechaza, con una razón escrita sobre la ROTACIÓN — instalar la mitad pública en el otro extremo.\n- Cambiar un interruptor de acceso. Ninguna petición que pueda componer tiene un campo para ellos.\n\nCompartir, sincronizar, copias de seguridad, recuperación, cuentas, llaves de seguridad, el informe de salud, importar y exportar, y el diario MCP son todos cosa de la persona y de nadie más, por diseño.",
  },
  'mcp-logs': {
    title: "MCP logs — el diario de los agentes",
    whatItIs: "Un diario de todo lo que los agentes de IA hicieron o pidieron a través de esta extensión: cada listado, cada uso, cada negativa — y dos cuentas que conviene vigilar: secretos que vinieron DESDE un agente, y peticiones que no pudimos atender.",
    why: "Un agente que actúa sobre sus credenciales debe dejar un rastro que una persona pueda leer después. La ventana de consentimiento muestra una acción; el diario muestra el patrón.",
    setup: "Nada que configurar. El diario se llena sólo cuando el acceso de agentes está encendido para al menos una entrada (vea «Agentes por MCP»).",
    usage: "Menú «…» del árbol → MCP logs. Cada línea nombra la entrada, la acción y el resultado; «Show Entry by id…» salta de una línea a la entrada que nombra.",
    whatCanGoWrong: "Un diario vacío con agentes configurados suele significar que ninguna entrada tiene sus interruptores encendidos — la escalera está apagada por defecto, también para las entradas que existían antes de esta función.",
  },
  'mcp-in-wsl': {
    title: "Ejecutar el servidor MCP desde dentro de WSL",
    whatItIs: "El `creds-mcp` de Linux dentro de su distribución no habla con la caja fuerte por sí mismo: relanza `creds-mcp.exe` en Windows a través de la interoperabilidad de WSL y transporta su stdio, de modo que un agente que vive en WSL alcanza la ventana que vive en Windows.",
    why: "Su editor y todos los secretos están en Windows, y `127.0.0.1` dentro de WSL2 es el loopback de la propia máquina virtual: allí no escucha nada nuestro, y los archivos de anuncio de la ventana están en un disco de Windows. Sin esto, a un agente se le dice «no CredsForDevs window answered» mientras la ventana está abierta en el mismo ordenador. Nada nuevo se pone a escuchar en ninguna parte: el puente es un proceso, no un socket.",
    setup: "Install… → **Install the MCP Server…** hace las dos mitades. Cuando esta máquina tiene WSL, pregunta *dónde corre el agente*: elija «Inside WSL — <su distribución>» e instalará el binario de Windows aquí, el de Linux allí (la misma línea publicada, que verifica la descarga y aterriza en `~/.local/bin`), le pedirá a la propia distribución la ruta de Windows — `wslpath`, nunca un `/mnt/c` adivinado — y dejará en su portapapeles un bloque de configuración que nombra el binario de LINUX con el de Windows en `env`. Péguelo en el cliente que corre DENTRO de esa distribución. Elija «This machine (Windows)» para un agente en una terminal de Windows, que es el comportamiento antiguo sin cambios. Mantenga abierta una ventana de VS Code con la caja fuerte desbloqueada; con ella habla cualquiera de las dos mitades. A mano en su lugar: Install… → *Copy install command for another machine…* → `creds-mcp` → «Linux, WSL or a container», y luego `claude mcp add -s user creds -e CREDS_MCP_WINDOWS_BINARY=/mnt/... -- ~/.local/bin/creds-mcp`.",
    usage: "`claude mcp list` dentro de WSL debería decir «creds ✔ Connected». A partir de ahí úselo exactamente igual que en Windows — las entradas, los interruptores, la ventana de consentimiento y el diario son los mismos, porque la llamada simplemente llega a través de un segundo proceso. La ventana sigue apareciendo en Windows, que es de lo que se trata.",
    whatCanGoWrong: "**Lo más frecuente es una versión publicada más antigua que el puente.** La instalación se lo advierte, porque el síntoma no lo hace: un binario así no alcanza Windows en absoluto e informa «No CredsForDevs window answered», palabra por palabra lo que dice una ventana cerrada. Medido contra el `mcp-v0.1.0` real. «creds-mcp.exe could not be started» significa que el binario de Windows no está donde el puente miró — ponga `CREDS_MCP_WINDOWS_BINARY` con su ruta `/mnt/...` completa. «No CredsForDevs window answered» entonces significa de verdad lo que dice: no hay ventana abierta, o la caja fuerte está bloqueada. Cada distribución necesita su propia copia del binario de Linux y su propio registro. Si su VS Code vive en un sitio poco habitual y usted define `CREDS_ENDPOINT_DIR`, nómbrelo en `WSLENV` (`export WSLENV=CREDS_ENDPOINT_DIR/p`) — las variables de entorno no cruzan solas a un hijo de Windows.",
  },
  'config-entities': {
    title: "Entradas de archivo de configuración",
    whatItIs: "Una entrada cuyo cuerpo es un archivo de configuración entero — appsettings.Development.json, un .env — mantenido fuera de git y sincronizado dentro de la caja fuerte como cualquier secreto.",
    why: "Estos archivos llevan cadenas de conexión con contraseñas dentro, y se pasaban a mano entre desarrolladores y se perdían.",
    setup: "Cree una entrada en una carpeta config (o elija el tipo Config) y pegue el archivo en Raw. Se guarda incluso mientras no parsea — la fila queda marcada hasta que lo haga.",
    usage: "Fields edita un valor sin tocar su formato. «Write Config File Here…» lo materializa en disco y rechaza una ruta seguida por git. «Enable Code Access…» acuña una clave (mostrada una sola vez) para que la aplicación lea la configuración al arrancar — el visor muestra el código exacto en veinte lenguajes y nombra el archivo al que va.\n\n**Show What Changed** compara la entrada con el archivo en disco, que es la pregunta que uno realmente tiene después de que alguien editó uno de los dos. **Revoke Code Access…** es el deshacer de la clave: la aplicación deja de leer la configuración al arrancar hasta que se acuñe y se pegue una nueva.",
    whatCanGoWrong: "La clave se muestra una vez y sólo se guarda su hash: si la pierde, acuñe otra. Escribir en una ruta seguida por git se rechaza a propósito — todo el sentido es que git nunca vea este archivo.",
  },
};
