import { HelpBody } from './helpContent';

/**
 * German bodies, one entry per article id.
 *
 * <p>Written against the English article rather than word for word: the catalog's shape is what
 * carries — what it is, why, how to set it up, how to use it, what can go wrong — and a sentence
 * that reads as a translation reads as a translation. Command names, setting keys and menu entries
 * stay in English, because that is what the person sees on screen.</p>
 *
 * <p>An article missing from this map falls back to English VISIBLY, which is the rule the catalog
 * has always had: a missing translation must never hide an article.</p>
 */
export const DE_BODIES: Readonly<Record<string, HelpBody>> = {
  'getting-started': {
    title: "Hier anfangen: ein Konto und der Ort, an dem sein Tresor lebt",
    whatItIs: "Ein Konto ist ein Tresor: eigener Baum, eigene Verschlüsselung, eigener Ort zum Leben. Eines anzulegen ist das Erste, was Sie tun — Ordner, Einträge und alles Weitere hängen daran.\n\nEin Tresor funktioniert vollständig auch ganz ohne Ort. Was ein Speicherort hinzufügt, ist eine zweite Maschine und andere Menschen.",
    why: "Alles wird auf Ihrer Maschine verschlüsselt, bevor es sie verlässt, der Ort hält also ausschließlich Geheimtext — die Wahl lohnt sich trotzdem am Anfang und nicht später, wenn schon mehrere Maschinen Kopien des alten Ortes halten.",
    setup: "Kontozeile -> **Add Account**, und anmelden. Dann auf diesem Konto -> **Set Sync Location…**, und eines von beidem wählen:\n\n- ein **Ordner** — jeder Pfad, den diese Maschine beschreiben kann: `Z:\\\\Backups`, `\\\\\\\\NAS\\\\Vault`, `/mnt/nas/vault`, oder ein Ordner, den etwas anderes bereits synchronisiert;\n- ein **Server** — die URL eines Cred Vault Server, `https://vault.company.com`.\n\nLassen Sie es leer, bleibt der Tresor auf dieser Maschine: alles funktioniert, nichts synchronisiert. Ein Git-Repository ist die dritte Möglichkeit und hat einen eigenen Artikel.",
    usage: "**Welches von beidem, und es ist keine Geschmacksfrage:**\n\n- Ein **Ordner**, wenn Sie es allein sind oder ein paar Leute, die ohnehin schon Speicher teilen. Nichts zu betreiben, nichts zu warten. Der Absender eines geteilten Eintrags gilt hier nach dem Prinzip Vertrauen beim ersten Kontakt — Sie lesen den Fingerabdruck einmal laut vor und merken ihn sich.\n- Ein **Server**, sobald mehr als eine Person beteiligt ist. Er stempelt den Absender einer Freigabe aus einer verifizierten Anmeldung, ein Absender lässt sich also nicht fälschen; er begrenzt Lesezugriffe auf Ihr eigenes Token; und Eintritt und Austritt folgen dem Identitätsanbieter, den Sie ohnehin haben.\n\nLesen kann keines von beiden. Was reist und was gespeichert wird, ist in beiden Fällen Geheimtext, und der Server hat keinen Schlüssel und keinen Codepfad, über den er einen bekäme.",
    whatCanGoWrong: "Ohne Speicherort ist nichts kaputt — der Tresor ist lokal und vollständig. Was fehlt, ist eine zweite Maschine oder das Teilen.\n\nDen Ort später zu ändern verschiebt die alte Datei nicht. Richten Sie den neuen auf denselben Ordner, oder synchronisieren Sie einmal von der Maschine, die die Daten noch hält.\n\n**Sign Out / Remove Account** nimmt das Konto von DIESER Maschine — den Baum, seine Tresordatei und die Schlüssel hier. Es ist keine Löschung auf dem Server oder im Sync-Ordner: melden Sie sich wieder an oder fügen Sie das Konto auf einer anderen Maschine hinzu, und der Baum ist zurück. **Reset Google OAuth** ist der kleinere Hammer für eine Anmeldung, die schiefgegangen ist — es vergisst das gespeicherte Client Secret und jede Google-Sitzung, lässt die Tresore in Ruhe, und die nächste Anmeldung beginnt sauber.\n\nBei einem Serverkonto liest **Server Metrics…** das eine JSON-Dokument, das der Server über sich selbst veröffentlicht. Wer nicht auf der Offiziersliste steht, bekommt die Absage des Servers, in Worten.\n\nEin Ort, der wie eine Git-Adresse aussieht — `git@…`, `ssh://…` oder eine Endung `.git` — wird ein Git-Tresor und kein Ordner. Das ist Absicht, und genau deshalb wird ein schlichtes `https://github.com/me/vault` NICHT erraten: es könnte ebenso gut eine Server-URL sein.",
  },
  'protection': {
    title: "Den Tresor abschließen: die PIN, ein Sicherheitsschlüssel, die Auto-Sperre",
    whatItIs: "Drei voneinander unabhängige Wege hinein und ein Timer, der entscheidet, wie lange ein entsperrter Tresor offen bleibt: eine **Sync-PIN**, ein oder mehrere **Sicherheitsschlüssel** (YubiKey / FIDO2) und ein gedruckter **Wiederherstellungscode**.",
    why: "Ein Tresor verschlüsselt seinen Inhalt mit einem zufälligen Hauptschlüssel, und dieser wird je Zugangsweg einmal eingepackt — eine Verpackung für die PIN, eine je registriertem Schlüssel. Jede Verpackung öffnet den Tresor, und deshalb verschlüsselt das Hinzufügen oder Entfernen eines Schlüssels Ihre Daten nie neu und macht die anderen nie ungültig.",
    setup: "- **Set Sync PIN** — dieselbe PIN auf jeder Maschine, die dieses Konto synchronisiert. Ohne sie lädt eine andere Maschine eine Datei herunter, die sie nicht öffnen kann.\n- **Add Security Key (YubiKey)…** in der Kontozeile. Das Betriebssystem zeigt seinen eigenen Dialog für Sicherheitsschlüssel, und das WebAuthn-PRF-Geheimnis des Schlüssels wird zum Verpackungsschlüssel. Registrieren Sie so viele, wie Sie möchten.\n- **Set Auto-Lock…** — Minuten IHRER Untätigkeit. 60 als Vorgabe; `0` sperrt nie.\n- **Set Up Recovery Code…** — der dritte Weg hinein, auf Papier. Hat einen eigenen Artikel, und lohnt sich, bevor Sie ihn brauchen.",
    usage: "Mit einem Schlüssel zu entsperren ist eine Berührung, im Stil einer Microsoft-Anmeldung — kein getipptes Passwort. Der Hauptschlüssel wird danach für das Fenster gehalten, die Hintergrundsynchronisation fragt also nie erneut. **Lock Vaults** verwirft ihn; **Unlock Vault (Security Key)…** fragt auf Wunsch.\n\nDie Auto-Sperre zählt IHRE Handlungen — Zugangsdaten öffnen oder kopieren, verbinden, einen Schlüssel installieren, bearbeiten, entsperren. Nicht Mausbewegungen und ausdrücklich nicht die Hintergrundsynchronisation: ein Fünf-Minuten-Timer, der als Aktivität zählte, hieße, dass das Leerlauffenster nie abläuft und die Einstellung stillschweigend nichts tut.\n\nSperren vergisst den Hauptschlüssel. Lokale Zugangsdaten funktionieren weiter, denn sie liegen im Schlüsselbund des Betriebssystems und sind nicht durch den Tresorschlüssel geschützt.",
    whatCanGoWrong: "Ohne PIN ist der Tresor praktisch lokal: eine andere Maschine kann die Datei herunterladen und nicht öffnen.\n\nDen letzten Sicherheitsschlüssel zu entfernen, wenn Sie die PIN vergessen haben, lässt den Wiederherstellungscode übrig — und sonst nichts. Das ist das Argument, ihn früh zu drucken.\n\n`autoLockMinutes: 0` sperrt nie. Das ist eine Möglichkeit, die jemand wollen kann, keine Vorgabe.",
  },
  'recovery-code': {
    title: "Der gedruckte Wiederherstellungscode",
    whatItIs: "Ein 150-Bit-Code, einmal gezeigt, gedruckt, auf Papier aufbewahrt — der dritte Weg in den Tresor für den Tag, an dem die PIN vergessen ist UND der Sicherheitsschlüssel weg.",
    why: "Die beiden alltäglichen Faktoren können gemeinsam ausfallen: eine vergessene PIN und ein verlorener YubiKey sind eine schlechte Woche, kein Paradox.",
    setup: "„Set Up Recovery Code…“ zeigt ihn einmal, mit Print und absichtlich ohne Copy: Zwischenablagen werden von Managern, Sync-Werkzeugen und Screenshot-Pipelines gelesen, und dieser Faktor muss das Notebook überleben.",
    usage: "„Unlock Vault (Recovery Code)…“, vom Papier abtippen — einen Tippfehler benennt die Prüfsumme lokal — und dann eine neue PIN setzen.",
    whatCanGoWrong: "Einen neuen Code zu erzeugen setzt den alten Ausdruck außer Kraft. Den letzten Sicherheitsschlüssel zu entfernen kann auch den Code außer Kraft setzen (das Neuverpacken braucht den Code, und der liegt auf Papier) — die Erweiterung sagt das inzwischen laut.",
  },
  'backup': {
    title: "Momentaufnahmen: datierte Kopien, die nie zusammengeführt werden",
    whatItIs: "Datierte Kopien des Tresors, in einen eigenen Speicher geschrieben, nach einem Zeitplan, den Sie wählen. Nicht dasselbe wie Synchronisation, und das mit Absicht.",
    why: "Synchronisation hält einen lebenden Tresor und FÜHRT ZUSAMMEN — was bedeutet, dass eine Löschung sich fortpflanzt. Löschen Sie Zugangsdaten auf dem Notebook, stimmt der nächste Abgleich am Desktop zu, dass sie weg sind. Für einen lebenden Tresor ist das richtig und als Sicherheitsnetz nutzlos, deshalb sind Momentaufnahmen ein zweiter, unabhängiger Weg, der nie zusammenführt und nie in jemandes Auftrag löscht.",
    setup: "- **Wohin** — `backupLocation`, oder pro Konto -> **Set Backup Location…**. Ein NAS-Ordner, eine externe Platte, **ein Google-Drive- oder OneDrive-Sync-Ordner** — alles, was diese Maschine beschreiben kann. Leer schaltet Momentaufnahmen ab.\n- **Wann** — `backupIntervalHours`: 24 täglich, 168 wöchentlich, `0` aus. Pro Konto -> **Set Backup Schedule…**. **Snapshot Vault Now** nimmt sofort eine auf.\n- **Wie lange** — `backupRetainDays`, 30 als Vorgabe; `0` behält alles.",
    usage: "**Momentaufnahmen funktionieren auch, wenn der Tresor auf einem Server liegt**, und die beiden sind absichtlich getrennte Einstellungen auf getrennten Speicher: ein Server ist der Dienst von jemandem, eine Momentaufnahme ist Ihre eigene Kopie Ihrer eigenen Daten.\n\nMomentaufnahmen in einen cloud-synchronisierten Ordner zu legen gibt Ihnen Verlauf außerhalb der Maschine, ohne irgendwem den Klartext zu geben — eine Momentaufnahme hat dasselbe verschlüsselte Format wie alles andere und öffnet sich mit dem Konto und der PIN.\n\nEine Momentaufnahme, die mit der vorherigen identisch ist, wird nicht geschrieben, ein stiller Tresor füllt also keinen kostenpflichtigen Ordner mit Kopien seiner selbst. Die neueste wird nie gelöscht, wie alt sie auch sei: ein Notebook, das ein Jahr zugeklappt war, darf nicht zu einem leeren Sicherungsordner zurückkehren.",
    whatCanGoWrong: "Momentaufnahmen an DENSELBEN Ort zu legen wie den Tresor hebt sie auf — das Sicherheitsnetz und das, was es auffangen soll, teilten sich einen Ausfall.\n\nMomentaufnahmen tragen Anhänge, Bilder und VPN-Konfigurationen ebenso wie Passwörter, der Ordner wächst also mit ihnen. Die Aufbewahrungsdauer ist das, was ihn begrenzt.",
  },
  'restore': {
    title: "Aus einer Momentaufnahme wiederherstellen",
    whatItIs: "Eine datierte Kopie zurück in ihr Konto lesen, aus dem ⋯-Menü des Baums -> **Import / Restore**.",
    why: "Die andere Hälfte des Sicherheitsnetzes. Eine Momentaufnahme, die niemand wiederherstellen kann, ist ein Ordner voller Dateien, und der Augenblick, in dem man merkt, dass sie sich nicht öffnet, ist nicht der Augenblick, in dem man sie braucht.",
    setup: "⋯ -> **Import / Restore**, die `.enc`-Datei wählen und beantworten, wonach gefragt wird. WELCHE Frage kommt, ist eine Eigenschaft der Datei, nicht des Befehls:\n\n- eine Momentaufnahme mit Schlüssel-Slots öffnet sich durch die eigene Tür des Tresors — eine Berührung des Sicherheitsschlüssels oder die PIN, dieselbe Tür, die auch die Synchronisation benutzt;\n- eine eigenständige Sicherung mit nur einem PIN-Slot verlangt die **Sicherungs-PIN, die beim Erstellen gesetzt wurde**, und eine Schlüsselberührung öffnet sie nicht. Der Dialog sagt das, denn sonst läse sich Schweigen so, als würde der Schlüssel ignoriert.",
    usage: "**Wiederherstellen ERSETZT den Baum dieses Kontos durch den der Momentaufnahme.** Es ist keine Zusammenführung: Einträge, die die Momentaufnahme nicht enthält, verschwinden samt ihren Geheimnissen. Genau das macht es zu einer Wiederherstellung und nicht zu einem Import — und deshalb probt man sicher an einem Wegwerfkonto und nicht an dem, das Sie benutzen.\n\nEine Momentaufnahme trägt alles: Anhänge, Bilder, VPN-Konfigurationen, Notizen und Versionsverlauf, nicht nur Passwörter.",
    whatCanGoWrong: "Eine Momentaufnahme aus einem neueren Build weigert sich, in einem älteren zu öffnen — *Unsupported backup version*. Erweiterung aktualisieren, dann wiederherstellen.\n\nLiegt das Konto an einem Sync-Ort, verbreitet eine alte Momentaufnahme mit anschließender Synchronisation genau diesen alten Zustand auf Ihre anderen Maschinen. Entscheiden Sie, welche Kopie die Wahrheit ist, bevor der nächste Abgleich läuft.",
  },
  'sync-vs-snapshots': {
    title: "Synchronisation und Momentaufnahmen sind verschiedene Maschinen",
    whatItIs: "Synchronisation führt eine verschlüsselte Datei pro Profil über Maschinen hinweg zusammen (kausal — zwei Maschinen, die gleichzeitig bearbeiten, laufen zusammen). Momentaufnahmen sind datierte Kopien, die nie zusammengeführt werden.",
    why: "Eine Zusammenführung pflanzt eine Löschung fort — das ist ihre Aufgabe. Die Momentaufnahme ist die Kopie, in der das Gelöschte noch steht.",
    setup: "Set Sync Location… pro Konto (Ordner, Server-URL oder ein Git-Repository). backupLocation auf ANDEREN Speicher richten. Dieselbe Sync-PIN auf jeder Maschine.",
    usage: "Sync Now, oder autoSync. Snapshot Vault Now für einen Punkt von Hand; Import / Restore, um zurückzukommen.",
    whatCanGoWrong: "Synchronisation und Momentaufnahmen in denselben Ordner hebt den Grund auf, warum es zwei gibt. Eine Wiederherstellung bringt den Tresor von DAMALS zurück — eine Synchronisation danach führt die neueren Änderungen wieder ein.",
  },
  'install-menu': {
    title: "Install… — was installiert wird und wohin",
    whatItIs: "Ein Untermenü, drei Installationen: die Terminal-CLI `creds` auf dieser Maschine, dieselbe CLI auf einer anderen Maschine (eine Zeile für Ihre Zwischenablage) und der Server `creds-mcp` für KI-Agenten.",
    why: "Die Erweiterung ist der Tresor; dies sind seine Türen für Terminals und Agenten. Keine davon kann ein Geheimnis halten oder beschaffen — sie reichen Anfragen an das VS-Code-Fenster weiter, dem der Eintrag gehört.",
    setup: "Menü „…“ des Baums → Install…. Jeder Punkt sagt, was er schreibt und wohin; der MCP-Punkt schreibt Ihnen zusätzlich den Konfigurationsblock des Clients.\n\n**Copy install command for another machine…** stellt zwei Fragen — welche Binärdatei (`creds` oder `creds-mcp`) und welche Maschine — und legt eine Bash- oder PowerShell-Zeile in Ihre Zwischenablage. Diese Zeile findet die neueste Veröffentlichung selbst und prüft den Download vor der Installation, hier muss also nichts die Version kennen.",
    usage: "Nach der Installation der CLI öffnen Sie einen Eintrag und führen „Enable CLI Access…“ aus, um einen Namen zu vergeben — danach `creds ssh <name>` aus jedem Terminal. Nach der Installation des MCP-Servers starten Sie Ihren MCP-Client neu und öffnen ihm Einträge über den Abschnitt Agent access.",
    whatCanGoWrong: "„No open window“ von `creds` heißt, dass kein VS-Code-Fenster mit der Erweiterung läuft oder der Zugriff auf den Eintrag nicht freigeschaltet wurde. Innerhalb von WSL wechselt der Aufruf automatisch nach Windows; tut er das nicht, fehlt die Windows-Binärdatei — aus demselben Menü neu installieren.",
  },
  'git-storage': {
    title: "Den Tresor in einem Git-Repository halten",
    whatItIs: "Eine dritte Art von Ort, neben einem Ordner und einem Server: ein privates Git-Remote. Der verschlüsselte Tresor ist eine Datei im Repository, und jede Synchronisation ist ein Pull und ein Push.",
    why: "Vielleicht haben Sie längst einen Ort, der privat, versioniert, gesichert und von überall erreichbar ist — und im Betrieb nichts kostet. Was Sie gegenüber einem Ordner dazubekommen, ist Geschichte: jede Version des Tresors ist ein Commit, eine schlechte Zusammenführung oder ein schlechter Tag ist also mit dem Werkzeug behebbar, das Ihr Team ohnehin kennt.",
    setup: "- Legen Sie ein **privates** Repository an. Leer ist gut; sonst kommt nichts hinein.\n- Am Konto -> **Set Sync Location…**, und geben Sie eine Adresse an, die unverkennbar Git ist: `git@github.com:me/vault.git`, `ssh://…`, oder jede Adresse, die auf `.git` endet. Ein schlichtes `https://github.com/me/vault` gilt absichtlich NICHT als Git — es sieht genau aus wie eine Server-URL.\n- **Die Anmeldung ist eine von zweien.** Über SSH richten Sie `gitDeployKeys` auf einen SSH-Schlüssel-Eintrag, der schon in Ihrem Tresor liegt — `{ \"git@github.com:me/vault.git\": \"<entry id>\" }` — und er wird nur für die Dauer des Aufrufs in eine private Datei geschrieben. Über HTTPS wird ein Token per Credential Helper über stdin geliefert, nie in der URL, wo es im Reflog und in den Protokollen jedes Remotes landen würde.",
    usage: "Danach ist es wie jeder andere Ort, und Git fassen Sie nicht mehr an: eine Synchronisation zieht, führt zusammen, committet und pusht von allein.\n\n- Alles lebt auf einem eigenen Branch, `creds-vault`, ein Repository, das Sie auch für anderes nutzen, wird also nicht gestört.\n- Eine `.gitattributes` markiert `*.enc` als binär, ohne Diff und ohne Merge. Git darf nie versuchen, zwei Geheimtexte Zeile für Zeile in Einklang zu bringen — die Zusammenführung macht die Erweiterung, auf dem entschlüsselten Baum, und erst danach wird wieder verschlüsselt.\n- Das Remote sieht Commits aus Geheimtext. GitHub, Ihre Kolleginnen und jeder, der klont, sehen dasselbe wie Sie: Bytes.",
    whatCanGoWrong: "Ein **öffentliches** Repository ist immer noch Geheimtext und immer noch eine schlechte Idee: es veröffentlicht Ihre Topologie — wie viele Einträge, wie oft Sie arbeiten, wann Sie etwas geändert haben.\n\nKann sich der Schlüssel oder das Token nicht anmelden, hält die Synchronisation an und sagt es. Nichts geht verloren; der Tresor ist lokal und vollständig, bis das Remote wieder antwortet.\n\nCommitten Sie nicht von Hand auf `creds-vault`. Dort schreibt ein Programm, das erwartet, der einzige Schreiber zu sein, und ein handgemachter Commit ist eine Zusammenführung, für die niemand entworfen hat.",
  },
  'basics': {
    title: "Einträge: die neun Arten, und was jede tut",
    whatItIs: "Konten halten Ordner, Ordner halten Einträge. Ein Eintrag ist eine Sache, die Sie benutzen — ein Host, eine Datenbank, ein Schlüssel — und seine Art entscheidet, was die Schaltfläche Connect darauf tatsächlich tut.",
    why: "Ein Passwortmanager speichert; dieser speichert und HANDELT dann. Deshalb zählt die Art: sie ist kein Etikett zum Sortieren, sondern die Handlung, die der Eintrag trägt.",
    setup: "Rechtsklick auf einen Ordner -> **Add Entry**, Art wählen, ausfüllen, was Sie haben. Ein typisierter Ordner entscheidet die Art für Sie. Rechtsklick -> **Edit** ändert später alles, und jeder Eintrag behält seine **letzten 3 Versionen**, eine Änderung ist also keine Einbahnstraße.\n\nZwei Dinge, die Sie sich nie selbst ausdenken müssen: ein **Passwort oder eine Passphrase**, mit einer Schaltfläche im Formular erzeugt, und ein **SSH-Schlüssel**, ebenso erzeugt, in sechs Typen (Ed25519 zuerst und empfohlen, drei ECDSA-Kurven, RSA 3072 und 4096).",
    usage: "**Die neun Arten:**\n\n- **credential** — ein Login, eine URL und ein Passwort. Die schlichte Art, für alles, was einfach ein Konto irgendwo ist.\n- **ssh** — ein Host: Benutzer, Port und entweder ein gespeicherter Schlüssel oder ein Passwort. Connect öffnet ein Terminal darauf.\n- **sshkey** — ein privater Schlüssel, hier erzeugt oder eingefügt. Installieren Sie ihn auf einem Host, oder laden Sie ihn in den Agenten, damit `ssh` und `git` ihn ohne Datei auf der Platte verwenden.\n- **vpn** — eine OpenVPN- oder WireGuard-Konfiguration. Tunnel aus dem Baum starten und stoppen.\n- **db** — eine Verbindung: Typ, Host, Port, Benutzer, Passwort. In Ihrem Datenbank-Client öffnen, oder eine Abfrage ausführen, ohne dass das Passwort je die Kommandozeile erreicht.\n- **terminal** — ein Befehl, den Sie gespeichert haben, mit seinen Argumenten als Zeilen und einer Notiz an jeder. Mit einem Klick ausführen, statt ihn sich zu merken.\n- **script** — ein Skript mit Hervorhebung bearbeitet, dessen `${NAME}`-Variablen als Zeilen herausgezogen und über die Umgebung geliefert statt in den Rumpf geklebt werden.\n- **config** — eine ganze Konfigurationsdatei, die der Tresor aus Git heraushält. Hat einen eigenen Artikel.\n- **payment** — eine Karte, Bankdaten oder eine Seed-Phrase, so zurückgelesen, wie sie gedruckt sind. Ebenfalls mit eigenem Artikel, denn eine Kartennummer ist kein Passwort und will nicht wie eines gezeigt werden.\n\nJeder Eintrag kann außerdem Notizen tragen, eine verschlüsselte Datei, ein Bild, einen Seed für Einmalcodes und eine **Lebensdauer** — eine Stunde, ein Tag, bis VS Code schließt — nach der er wirklich gelöscht und nicht als verbraucht markiert wird.\n\n**In der Zeile selbst:** *View Details* öffnet den Eintrag schreibgeschützt, sodass Sie schauen können, ohne ein Bearbeitungsformular; *Move to Folder…* legt ihn um (und *Move Up* / *Move Down* ordnen von Hand); *Toggle SSH (on/off)* kippt den SSH-Schalter des einzelnen Eintrags, der bei einem neuen Eintrag aus ist; *Save VPN Config As…* schreibt die Konfiguration eines VPN-Eintrags in eine Datei, für einen Client, der darauf besteht.",
    whatCanGoWrong: "Ein typisierter Ordner verweigert eine Art, die er nicht hält; verschieben Sie den Eintrag oder nehmen Sie einen Ordner vom Typ *any*.\n\nEinen Schlüssel zu erzeugen heißt nicht, ihn zu installieren: die öffentliche Hälfte muss noch zum Host gelangen, und genau dafür ist **Install SSH Key** da.",
  },
  'import-existing': {
    title: "Hereinholen, was Sie schon haben",
    whatItIs: "Ihre vorhandenen Hosts und Logins aus `~/.ssh/config` oder aus einem anderen Passwortmanager einlesen, statt sie abzutippen.",
    why: "Ein Tresor, den man von Hand füllen muss, bleibt leer, und halb gefüllt ist schlimmer als beides: sobald zwei Orte Ihre Zugangsdaten halten, wird keinem davon getraut.",
    setup: "Rechtsklick auf ein Konto -> **Import from ~/.ssh/config or another manager…**, und die Datei wählen. Was herüberkommt:\n\n- **`~/.ssh/config`** — Host, HostName, User, Port, IdentityFile, als verbindungsfähige SSH-Einträge.\n- **Bitwarden, KeePass, LastPass, Termius (CSV)** — Name, Benutzername, Passwort, Adresse, Notizen, Einmalcode-Seed, Ordner.\n- **Bitwarden, 1Password (JSON)** — dasselbe, aus Login-Einträgen.\n\n**Import from External…** ist die Gegenrichtung von *Export / Share Externally* — eine versiegelte Datei, die Ihnen jemand geschickt hat.",
    usage: "Der INHALT der Datei entscheidet, wie sie gelesen wird, ein falsch benannter Export lässt sich also trotzdem importieren.\n\nNichts landet, bevor Sie die Anzahl gesehen haben und das, was übersprungen wird — und übersprungene Zeilen werden mit Grund aufgeführt, statt still zu verschwinden. Alles bekommt eine frische Id, ein Import kann also nie überschreiben, was Sie schon hatten.",
    whatCanGoWrong: "**KDBX — die eigene Datenbank von KeePass — wird bewusst nicht gelesen**: sie ist mit Argon2 verschlüsselt, Argon2 gibt es in Node nicht, und eine halb richtige Umsetzung davon wäre schlimmer als gar keine. KeePass exportiert CSV, und das importiert einwandfrei.\n\nEin Import fügt hinzu; er führt nie mit dem Vorhandenen zusammen. Zwei Importe derselben Datei geben Ihnen zwei Kopien, denn eine frische Id ist genau das, was verhindert, dass der erste überschrieben wird.",
  },
  'trash': {
    title: "Der Papierkorb: löschen und zurückholen",
    whatItIs: "Einen Eintrag oder einen Ordner zu löschen verschiebt ihn in den Papierkorb — einen Ordner wie jeder andere, den Sie öffnen, hineinsehen und aus dem Sie herausziehen können. Weg ist es, wenn der Papierkorb geleert wird, und nicht früher.",
    why: "Eine Löschung SYNCHRONISIERT. Löschen Sie auf dem Notebook, stimmt der nächste Abgleich am Desktop zu, dass es weg ist, überall, samt Verlauf. Der Papierkorb ist das Fenster, in dem dieser Fehler noch Ihrer ist.",
    setup: "Rechtsklick -> **Delete**. Um zu entscheiden, wie lange Dinge dort liegen: ⋯ -> **Empty the Trash Automatically…**. Um sofort zu leeren: **Empty the Trash Now**.",
    usage: "- **Restore** legt einen Eintrag dorthin zurück, WOHER er gelöscht wurde, nicht in die Wurzel — und **Go to the Original Folder** zeigt Ihnen vorher, wo das ist.\n- Ordner werden ebenso wiederhergestellt, und der Baum zeigt, was zurückkam.\n- **Nichts im Papierkorb antwortet einem Agenten**, was seine Schalter auch sagen. Ein gelöschtes Ding, das noch funktioniert, machte das Wort bedeutungslos.\n\nEin Eintrag mit Lebensdauer ist die Ausnahme: **Burn Now…** darauf ist eine echte Löschung und keine Verschiebung — das Geheimnis, seine aufbewahrten Versionen und, per Grabstein, jede synchronisierte Kopie. Der Dialog sagt das, bevor Sie zustimmen.",
    whatCanGoWrong: "Leeren ist endgültig und es synchronisiert: hinter dem ersten Papierkorb gibt es keinen zweiten.\n\nEin Eintrag, der wiederhergestellt wird, nachdem sein ursprünglicher Ordner selbst gelöscht wurde, landet in der Wurzel — den Ort, von dem er kam, gibt es nicht mehr.",
  },
  'project-folders': {
    title: "Projektordner: der ganze Satz mit einem Klick",
    whatItIs: "Ein Ordner vom Typ **project** ist ein Behälter für ein Stück Arbeit, und ihn anzulegen stellt den typisierten Satz sofort darin auf: Datenbanken, VPNs, SSH-Schlüssel, SSH-Verbindungen, Passwörter, Terminalbefehle, Skripte, Konfigurationsdateien und Zahlungsdaten.",
    why: "Was ein Projekt braucht, ist selten von einer Art. Jedes Mal neun Ordner von Hand anzulegen ist die Sorte Pflicht, die Leute auslassen, und ein Tresor, in dem Ähnliches in verschiedenen Formen liegt, ist ein Tresor, in dem niemand etwas findet.",
    setup: "Rechtsklick auf ein Konto oder einen Ordner -> **Add Folder**, und den Typ auf **project** setzen. Der Satz erscheint sofort darin. **Change Folder Type…** wandelt einen vorhandenen Ordner um.",
    usage: "Der Typ ist es, der den Baum vorhersagbar macht: ein typisierter Unterordner entscheidet die Art der Einträge, die Sie hineinlegen, *Add Entry* in `db` gibt Ihnen also eine Datenbank und keine Frage.\n\n`project` selbst schreibt über Einträge nichts vor — es ist ein reiner Ordnertyp, und seine eigenen Einträge auf eine Art namens „project“ zu zwingen hieße, eine Entitätsart zu erfinden, die es nicht gibt. Die Bedeutung trägt die Form dessen, was er aufstellt.\n\nAgentenzugriff, der auf einem Projektordner gesetzt wird, vererbt sich auf alles darunter, und genau das macht ihn zur natürlichen Einheit, die man einem Agenten öffnet: ein Schalter, ein Projekt.",
    whatCanGoWrong: "Die aufgestellten Ordner sind gewöhnliche Ordner. Löschen Sie die, die Sie nicht brauchen — nichts hängt davon ab, dass alle neun existieren.",
  },
  'share-with-agent': {
    title: "Share with Claude Code",
    whatItIs: "Einem KI-Agenten den GEBRAUCH einer Zugangsdatei geben, ohne ihm die Zugangsdatei zu geben. Rechtsklick auf einen Eintrag -> **Share with Claude Code…**: ein Befugnis-Token wird geprägt und ein einfügefertiger Schnipsel landet in Ihrer Zwischenablage.",
    why: "Ein Passwort in einen Chat zu kleben legt den Klartext in ein Protokoll und in jedes Log flussabwärts davon; es in eine Datei zu exportieren ist nicht besser. Der Agent bittet das Fenster zu handeln, das Fenster handelt, und zurück kommt allein das Ergebnis — im Protokoll gibt es kein Feld, in dem ein Geheimnis reisen könnte.",
    setup: "Rechtsklick auf jeden Eintrag, mit dem ein Agent etwas TUN kann — SSH-Hosts, Skripte, Terminalbefehle, Datenbanken, VPN-Tunnel, gewöhnliche Zugangsdaten -> **Share with Claude Code…**, dann geben Sie dem Agenten, was in Ihrer Zwischenablage liegt.\n\nDas Token benennt EINEN Eintrag und stirbt mit dem VS-Code-Fenster, das es geprägt hat. Die erste Verwendung fragt Sie um einen Klick.\n\nZwei Grenzen verkürzen dieses Leben weiter, und beide sind Einstellungen, die Sie ändern können: `agentGrantIdleMinutes` lässt ein ungenutztes Token verfallen — eines, mit dem ein Agent aktiv arbeitet, erneuert sich laufend — und `agentGrantMaxCalls` deckelt, wie viele Aufrufe ein Token überhaupt machen darf, die Obergrenze für ein Token, das Sie für eine bestimmte Aufgabe herausgeben.",
    usage: "Was der Agent dann verlangen kann, je ein Verb: einen Befehl auf dem Host ausführen, das interaktive Terminal **für Sie** öffnen, eine Abfrage ausführen, Ihr gespeichertes Skript oder Ihren Befehl ausführen, das Geheimnis in neue Terminals exportieren, ein VPN hochfahren.\n\n**Zwei davon ignorieren absichtlich, was der Agent sendet.** `script` und `run` führen genau das aus, was Sie gespeichert haben, also erreicht kein vom Agenten verfasster Text je eine Shell oder einen Interpreter. Sie verlangen außerdem, dass Sie den Eintrag auf dieser Maschine selbst einmal ausgeführt haben — ein Allow deckt ein Token, keinen Rumpf, und ein Rumpf kann nach Ihrem Klick von einer Synchronisation ersetzt werden.\n\nDas ist nicht dasselbe wie MCP. Ein Share ist ein Eintrag, ein Token, dieses Fenster; MCP ist eine stehende Fläche mit Schaltern pro Eintrag. Beide lösen dieselbe Zustimmungsabfrage aus, und beide stehen in den **MCP logs**.",
    whatCanGoWrong: "Das Token ist an das Fenster gebunden, das es geprägt hat: nach einem Neuladen wird dem Agenten gesagt, er solle ein neues erbitten. Das ist die vorgesehene Lebensdauer, kein Fehler.\n\nDer Agent muss das Loopback dieser Maschine erreichen können. Einer, der in einem Container läuft, kann das nicht — führen Sie ihn für diese Funktion also auf dem Client aus.\n\nMongoDB wird bewusst abgelehnt: `mongosh` hat keine Passwort-Umgebungsvariable, und sein `--eval` läuft in demselben Interpreter, der die Umgebung lesen kann — eine „Abfrage\" könnte die Zugangsdaten zurückdrucken.",
  },
  'agents-mcp': {
    title: "Agenten über MCP — die zwei Leitern",
    whatItIs: "Zwei Leitern, zehn Schalter. Über EINTRÄGE: sehen, benutzen, das Geheimnis ersetzen, Einträge anlegen, Selbstangelegtes löschen, alles löschen. Über ORDNER: anlegen, umbenennen und verschieben, Selbstangelegtes löschen, jeden löschen. Alle standardmäßig aus, und vererbt an alles unterhalb des Ordners, an dem Sie sie setzen.",
    why: "Ein Agent soll genau das erreichen, was Sie geöffnet haben, und nichts weiter — und „geöffnet\" soll am Eintrag selbst sichtbar sein, nicht in einer Konfigurationsdatei vergraben.",
    setup: "Eintrag bearbeiten → Abschnitt Agent access (MCP), oder setzen Sie die Schalter an einem Ordner und lassen die Einträge sie erben. Den Server installieren Sie über Install… → Install the MCP Server.",
    usage: "Der Baum markiert einen geöffneten Eintrag mit einem Fünfeck — jede leuchtende Kante ein Schalter der Eintragsleiter. Rotation läuft über einen `{{creds:new}}`-Platzhalter, es gelangt also nie ein Wert in den Kontext des Agenten. Ein Agent darf außerdem sagen, wie ein erzeugtes Geheimnis AUSSEHEN soll — Länge, welche Zeichensätze, wie viele Wörter — was zählt, wenn die Gegenseite die Länge begrenzt oder Symbole verbietet; die Abfrage zeigt Ihnen, worum er gebeten hat. Ordner sieht ein Agent über `creds_folders` und ändert sie mit `creds_create_folder` / `creds_edit_folder` / `creds_delete_folder`. Jede Handlung löst weiterhin die Zustimmungsabfrage aus.\n\nWas der Agent auch ausführt, die Antwort wird auf dem Weg hinaus maskiert: eine einzige Engstelle ersetzt die eigenen gespeicherten Werte dieses Eintrags im Antwortrumpf, bevor er das Fenster verlässt, und die Auditzeile meldet, wie viele sie erwischt hat. Ein Befehl, der sein Passwort zurückwirft, reicht dem Agenten also eine Maske, nicht das Passwort.",
    whatCanGoWrong: "Der Schalter ist die Erlaubnis zu FRAGEN, nicht die Zustimmung — wenn die Abfrage Sie überrascht, arbeitet sie. Nichts im Papierkorb antwortet Agenten, welche Schalter auch immer daran stehen. Sieht ein Agent eine leere Liste, ist kein Schalter an. **Ein Agent kann niemals einen Schalter ändern**: keine Anfrage, die er stellen kann, trägt das Feld, Ordner bearbeiten heißt also Name, Ort und Typ und sonst nichts. Ein Verschieben braucht die Erlaubnis an beiden Enden, denn ein Ordner reicht seine Antworten an alles darin weiter.",
  },
  'agent-surface': {
    title: "Was ein Agent kann und was nicht",
    whatItIs: "Die Karte der Agentenfläche dieses Tresors, aus dem Code genommen und nicht aus dem Gedächtnis: 9 Arten von Einträgen, 16 MCP-Werkzeuge, 10 Zugriffsschalter, über 100 Befehle in der Erweiterung.\n\nDrei Zustände lohnt es zu unterscheiden. **Ausdrücklich** — es gibt ein Werkzeug dafür. **Implizit** — ein Agent bekommt es als Folge eines anderen Aufrufs, ohne eigenes Werkzeug. **Gar nicht** — überhaupt nicht erreichbar.",
    why: "**Die Asymmetrie, die man zuerst kennen sollte:** ein Agent kann einen Eintrag ANLEGEN und LÖSCHEN und sein Geheimnis ersetzen — aber kein gewöhnliches Feld davon BEARBEITEN: nicht den Namen, nicht den Host, nicht den Benutzer, nicht den Port. Ordner haben seit 0.85.0 den vollen Satz: anlegen, umbenennen, verschieben, löschen.\n\nEin Agent, der Infrastruktur bereitstellt, kann also einen Ordnerbaum bauen und ihn füllen und einen selbst gemachten Tippfehler nicht korrigieren — nur löschen und neu anlegen, unter Verlust der Versionsgeschichte.",
    setup: "Für die Karte selbst gibt es nichts einzurichten. Was ein Agent tatsächlich erreicht, entscheiden die Schalter an einem Eintrag oder an einem Ordner — siehe den Artikel über Agenten via MCP, der die zwei Leitern und ihre Vererbung erklärt.",
    usage: "**Ausdrücklich — ein eigenes Werkzeug:**\n\n- creds_list — Einträge: Name, Art, Ordner, Host, Port, Benutzer, Datenbanktyp, ein Verbindungsstring ohne Passwort, Abhängigkeiten. hasPassword, hasPrivateKey, hasNotes und hasTotp sagen, dass etwas existiert, nie was es ist.\n- creds_folders — Ordner: id, Name, Elternteil, Typ, und was mit jedem getan werden darf.\n- creds_exec, creds_query, creds_run, creds_open_terminal, creds_vpn_up, creds_vpn_down — eine Zugangsdatei benutzen, ohne sie je zu erhalten.\n- creds_rotate — ein Geheimnis über einen {{creds:new}}-Platzhalter ersetzen. **Nur für db- und ssh-Einträge**; credential, vpn, terminal, script, config, payment und sshkey lassen sich nicht rotieren.\n- creds_create, creds_delete — und seit 0.86.0 die Gestalt eines erzeugten Geheimnisses: Länge, Zeichensätze, Wortzahl.\n- creds_create_folder, creds_edit_folder, creds_delete_folder — Ordner, seit 0.85.0.\n- creds_config_snippet — wie Code einen config-Eintrag liest. Öffentlicher Text; der Inhalt der Konfiguration wird nie zurückgegeben.\n\n**Implizit — was ein Aufruf über seinen Namen hinaus gewährt:**\n\n- creds_exec ist eine volle Shell auf diesem Host mit den Rechten dieses Benutzers: Pakete installieren, Dateien lesen, ausgehendes Netz. Die weiteste Berechtigung im Satz.\n- creds_query ist beliebiges SQL: jede Tabelle, DDL, und Rechte innerhalb der Datenbank selbst.\n- creds_run führt Code aus, den jemand anderes geschrieben hat — die Person hat ihn gespeichert, der Agent wählt wann.\n- creds_rotate schreibt in die Versionsgeschichte: der alte Wert bleibt dort, der neue im Tresor.\n- creds_create mit einem ausdrücklichen Geheimnis ist der eine Weg, auf dem ein Geheimnis von einem Agenten IN den Tresor fließt. Das Journal zählt solche Zeilen getrennt.\n- Anlegen in einem typisierten Ordner: der Ordner diktiert die Art, nicht der Agent.\n- Einen Ordner zu verschieben ändert die Rechte von allem darin, weshalb die Erlaubnis an beiden Enden nötig ist.\n- Löschen startet die Papierkorb-Uhr. „Umkehrbar\" gilt, bis er sich leert; für einen Eintrag mit Lebensdauer ist das Löschen sofort endgültig.\n- creds_export_env ändert, was das nächste Terminal der Person sehen wird.",
    whatCanGoWrong: "**Woran ein Agent stößt und was er nicht kann:**\n\n- Felder eines Eintrags bearbeiten — Name, Host, Benutzer, Port, Notizen. Nur löschen und neu anlegen.\n- Etwas anderes als einen db- oder ssh-Eintrag rotieren.\n- Ein Geheimnis, eine Notiz, eine VPN-Konfiguration oder einen Seed für Einmalcodes lesen — strukturell gibt es kein Feld, in dem sie reisen könnten.\n- Einen Einmalcode benutzen. creds_list sagt, hasTotp sei wahr, und es gibt kein Werkzeug, ein Agent, der eine Anmeldung zu Ende bringt, hält also genau hier an.\n- Aus dem Papierkorb wiederherstellen. Er kann löschen und nicht rückgängig machen.\n- Dem, was er anlegt, eine Lebensdauer geben.\n- Ein SSH-Schlüsselpaar erzeugen. Die Erweiterung macht sechs Typen im Eintragsformular; einem Agenten wird das verweigert, mit einer Begründung, die von ROTATION handelt — die öffentliche Hälfte auf der Gegenseite zu installieren.\n- Einen Zugriffsschalter ändern. Keine Anfrage, die er bilden kann, hat ein Feld dafür.\n\nTeilen, Synchronisation, Sicherungen, Wiederherstellung, Konten, Sicherheitsschlüssel, der Gesundheitsbericht, Import und Export und das MCP-Journal gehören alle allein der Person, so entworfen.",
  },
  'mcp-logs': {
    title: "MCP logs — das Agentenjournal",
    whatItIs: "Ein Journal von allem, was KI-Agenten durch diese Erweiterung getan oder erbeten haben: jede Auflistung, jede Verwendung, jede Ablehnung — und zwei Zahlen, die zu beobachten sich lohnt: Geheimnisse, die VON einem Agenten kamen, und Anfragen, die wir nicht bedienen konnten.",
    why: "Ein Agent, der mit Ihren Zugangsdaten handelt, muss eine Spur hinterlassen, die ein Mensch hinterher lesen kann. Die Zustimmungsabfrage zeigt eine Handlung; das Journal zeigt das Muster.",
    setup: "Nichts einzurichten. Das Journal füllt sich erst, wenn der Agentenzugriff für mindestens einen Eintrag an ist (siehe „Agenten über MCP\").",
    usage: "Menü „…\" des Baums → MCP logs. Jede Zeile nennt den Eintrag, die Handlung und den Ausgang; „Show Entry by id…\" springt von einer Zeile zu dem Eintrag, den sie nennt.",
    whatCanGoWrong: "Ein leeres Journal bei eingerichteten Agenten heißt meist, dass an keinem Eintrag die Schalter an sind — die Leiter ist standardmäßig aus, auch für Einträge, die es vor der Funktion schon gab.",
  },
  'mcp-in-wsl': {
    title: "Den MCP-Server aus WSL heraus betreiben",
    whatItIs: "Das Linux-`creds-mcp` in Ihrer Distribution spricht nicht selbst mit dem Tresor: es startet `creds-mcp.exe` auf Windows über WSL-Interop neu und trägt dessen stdio, sodass ein Agent, der in WSL lebt, das Fenster erreicht, das auf Windows lebt.",
    why: "Ihr Editor und jedes Geheimnis liegen auf Windows, und `127.0.0.1` innerhalb von WSL2 ist das Loopback der virtuellen Maschine selbst — dort lauscht nichts von uns, und die Ankündigungsdateien des Fensters liegen auf einer Windows-Platte. Ohne das bekommt ein Agent „no CredsForDevs window answered\" zu hören, während das Fenster auf demselben Rechner offen steht. Nirgends lauscht etwas Neues: die Brücke ist ein Prozess, kein Socket.",
    setup: "Install… → **Install the MCP Server…** erledigt beide Hälften. Hat diese Maschine WSL, fragt es, *wo der Agent läuft*: wählen Sie „Inside WSL — <Ihre Distribution>\", und es installiert die Windows-Binärdatei hier, die Linux-Binärdatei dort (mit derselben veröffentlichten Einzeiler-Zeile, die den Download prüft und in `~/.local/bin` landet), fragt die Distribution selbst nach dem Windows-Pfad — `wslpath`, nie ein geratenes `/mnt/c` — und legt einen Konfigurationsblock in Ihre Zwischenablage, der die LINUX-Binärdatei nennt und die Windows-Binärdatei in `env` mitgibt. Fügen Sie ihn in den Client ein, der INNERHALB dieser Distribution läuft. Für einen Agenten in einem Windows-Terminal wählen Sie „This machine (Windows)\" — das alte, unveränderte Verhalten. Halten Sie ein VS-Code-Fenster mit entsperrtem Tresor offen; mit ihm spricht jede der beiden Hälften. Von Hand stattdessen: Install… → *Copy install command for another machine…* → `creds-mcp` → „Linux, WSL or a container\", dann `claude mcp add -s user creds -e CREDS_MCP_WINDOWS_BINARY=/mnt/... -- ~/.local/bin/creds-mcp`.",
    usage: "`claude mcp list` innerhalb von WSL sollte „creds ✔ Connected\" sagen. Danach benutzen Sie es genau wie auf Windows — die Einträge, die Schalter, die Zustimmungsabfrage und das Journal sind dieselben, weil der Aufruf lediglich durch einen zweiten Prozess ankommt. Die Abfrage erscheint weiterhin auf Windows, und genau darum geht es.",
    whatCanGoWrong: "**Der häufigste Fall ist eine veröffentlichte Version, die älter ist als die Brücke.** Die Installation warnt Sie davor, denn das Symptom tut es nicht: eine solche Binärdatei erreicht Windows überhaupt nicht und meldet „No CredsForDevs window answered\" — Wort für Wort das, was ein geschlossenes Fenster meldet. Gemessen am echten `mcp-v0.1.0`. „creds-mcp.exe could not be started\" heißt, die Windows-Binärdatei liegt nicht dort, wo die Brücke gesucht hat — setzen Sie `CREDS_MCP_WINDOWS_BINARY` auf ihren vollen `/mnt/...`-Pfad. „No CredsForDevs window answered\" bedeutet dann wirklich, was es sagt: kein Fenster offen, oder der Tresor gesperrt. Jede Distribution braucht ihre eigene Kopie der Linux-Binärdatei und ihre eigene Registrierung. Wohnt Ihr VS Code an einem ungewöhnlichen Ort und Sie setzen `CREDS_ENDPOINT_DIR`, nennen Sie es in `WSLENV` (`export WSLENV=CREDS_ENDPOINT_DIR/p`) — Umgebungsvariablen wandern nicht von allein in ein Windows-Kind.",
  },
  'config-entities': {
    title: "Konfigurationsdatei-Einträge",
    whatItIs: "Ein Eintrag, dessen Rumpf eine ganze Konfigurationsdatei ist — appsettings.Development.json, eine .env — aus Git herausgehalten und im Tresor synchronisiert wie jedes Geheimnis.",
    why: "Diese Dateien enthalten Verbindungsstrings mit Passwörtern darin, und sie wurden von Hand zwischen Entwicklern weitergereicht und gingen verloren.",
    setup: "Legen Sie einen Eintrag in einem config-Ordner an (oder wählen Sie den Typ Config) und fügen Sie die Datei in Raw ein. Sie speichert auch, solange sie nicht parst — die Zeile bleibt markiert, bis sie es tut.",
    usage: "Fields ändert einen einzelnen Wert, ohne Ihre Formatierung anzutasten. „Write Config File Here…\" schreibt sie auf die Platte und verweigert einen von Git verfolgten Pfad. „Enable Code Access…\" prägt einen Schlüssel (einmal gezeigt), damit die Anwendung die Konfiguration beim Start liest — der Betrachter zeigt den genauen Code in zwanzig Sprachen und nennt die Datei, in die er gehört.\n\n**Show What Changed** vergleicht den Eintrag mit der Datei auf der Platte, was die Frage ist, die Sie tatsächlich haben, nachdem jemand eine von beiden bearbeitet hat. **Revoke Code Access…** ist das Rückgängig des Schlüssels: die Anwendung liest die Konfiguration beim Start nicht mehr, bis ein neuer geprägt und eingefügt ist.",
    whatCanGoWrong: "Der Schlüssel wird einmal gezeigt und nur sein Hash behalten: verlieren Sie ihn, prägen Sie einen neuen. Das Schreiben in einen verfolgten Pfad wird absichtlich verweigert — der ganze Sinn ist, dass Git diese Datei nie sieht.",
  },
};
