using System.Text.Json;
using System.Text.Json.Serialization;

namespace CredsBroker;

/// <summary>
/// The broker's wire contract, read from the JSON generated by the TypeScript that defines it.
/// </summary>
/// <remarks>
/// <para>The moment this binary exists, the protocol stops being a shared module and becomes a
/// specification with two implementations. This is the half that stops them drifting: the file
/// is generated from <c>brokerProtocol.ts</c>, embedded here at build time, and a test on each
/// side asserts its own tables match it. A divergence fails a build instead of surfacing as a
/// puzzling exit code in somebody's terminal.</para>
/// <para>Read once into <see cref="Current"/>. Parsing is a few microseconds on a payload this
/// size, and doing it at startup keeps the failure — a corrupt or missing resource — at the one
/// moment nothing has happened yet.</para>
/// </remarks>
public sealed record BrokerContract(
    [property: JsonPropertyName("version")] int Version,
    [property: JsonPropertyName("service")] string Service,
    [property: JsonPropertyName("health")] HealthRoute Health,
    [property: JsonPropertyName("limits")] Dictionary<string, int> Limits,
    [property: JsonPropertyName("routes")] Dictionary<string, string> Routes,
    [property: JsonPropertyName("reads")] Dictionary<string, ReadEndpoint>? Reads,
    [property: JsonPropertyName("mcpUsePrefix")] string? McpUsePrefix,
    [property: JsonPropertyName("mcpActions")] string[]? McpActions,
    [property: JsonPropertyName("mcpFolderPrefix")] string? McpFolderPrefix,
    [property: JsonPropertyName("mcpFolderActions")] string[]? McpFolderActions,
    [property: JsonPropertyName("mcpDeleteRoute")] string? McpDeleteRoute,
    [property: JsonPropertyName("mcpCreateRoute")] string? McpCreateRoute,
    [property: JsonPropertyName("configRead")] ConfigReadRoute? ConfigRead,
    [property: JsonPropertyName("errors")] Dictionary<string, int> Errors,
    [property: JsonPropertyName("exitCodes")] Dictionary<string, int> ExitCodes)
{
    private static readonly Lazy<BrokerContract> Loaded = new(Load);

    public static BrokerContract Current => Loaded.Value;

    private static BrokerContract Load()
    {
        using var stream =
            typeof(BrokerContract).Assembly.GetManifestResourceStream("broker-v1.json")
            ?? throw new InvalidOperationException(
                "broker-v1.json is not embedded in this binary — the build is broken, not your setup.");

        return JsonSerializer.Deserialize(stream, BrokerJsonContext.Default.BrokerContract)
            ?? throw new InvalidOperationException("broker-v1.json is embedded but unreadable.");
    }

    /// <summary>The route a verb posts to, or <c>null</c> when this build has no such verb.</summary>
    public string? RouteFor(string verb) => Routes.TryGetValue(verb, out var route) ? route : null;

    /// <summary>
    /// A read route by name — the GET endpoints that perform nothing and carry no token.
    /// </summary>
    /// <remarks>
    /// Nullable and defaulted because a contract file written before this section existed is a
    /// real thing to meet: the resource is embedded at build time and so is always in step here,
    /// but a copy read from somewhere else must degrade to the path this build knows rather than
    /// throwing on a missing key. The fallback is the value that was hard-coded before.
    /// </remarks>
    public string ReadRoute(string name, string fallback) =>
        Reads is not null && Reads.TryGetValue(name, out var route) ? route.Path : fallback;

    /// <summary>
    /// The verb a read is served with.
    /// </summary>
    /// <remarks>
    /// <para>It exists because inferring it cost five releases. `mcpFolders` was filed under
    /// <see cref="Reads"/>, where every client GETs, and served by the window under POST alone —
    /// so it answered 404 from extension 0.85.0 to 0.89.0 and the whole folder surface with it.
    /// Both sides had a test asserting they meant the same PATH and neither could assert the
    /// verb, because the contract had no field for one.</para>
    /// <para>Defaults to GET rather than throwing, like every other accessor here: a contract
    /// file written before this field existed must degrade to what this build knows.</para>
    /// </remarks>
    public string ReadMethod(string name) =>
        Reads is not null && Reads.TryGetValue(name, out var route) && route.Method is { Length: > 0 }
            ? route.Method
            : "GET";

    /// <summary>
    /// Where an MCP client posts one action.
    /// </summary>
    /// <remarks>
    /// A prefix plus the action, rather than a route per verb: the verb vocabulary is
    /// <see cref="Routes"/> and repeating it would be two lists to keep in step. Nullable with a
    /// fallback for the same reason <see cref="ReadRoute"/> is — a contract file written before
    /// this section existed must degrade to the path this build knows.
    /// </remarks>
    public string McpUseRoute(string action) =>
        (McpUsePrefix is { Length: > 0 } prefix ? prefix : "/v1/mcp/use/") + action;

    /// <summary>
    /// Where an agent posts a deletion.
    /// </summary>
    /// <remarks>
    /// A route rather than an action under the use prefix, because deleting is not a use of a
    /// credential. Nullable with a fallback for the same reason the others are: a contract file
    /// written before this line existed must degrade to the path this build knows.
    /// </remarks>
    public string DeleteRoute() => McpDeleteRoute is { Length: > 0 } route ? route : "/v1/mcp/delete";

    /// <summary>Where an agent posts a new entry. The only body that names no entry.</summary>
    public string CreateRoute() => McpCreateRoute is { Length: > 0 } route ? route : "/v1/mcp/create";

    /// <summary>
    /// Where an agent posts one folder verb.
    /// </summary>
    /// <remarks>
    /// A prefix plus the verb, exactly as the use routes are, and nullable with a fallback for
    /// the same reason every route here is: a contract file written before this line existed
    /// must degrade to the path this build knows rather than throwing on a missing key.
    /// </remarks>
    public string FolderRoute(string action) =>
        (McpFolderPrefix is { Length: > 0 } prefix ? prefix : "/v1/mcp/folder/") + action;

    /// <summary>
    /// Where an application reads one config file.
    /// </summary>
    /// <remarks>
    /// The one authenticated route on that server which is not a use, and the only POST that
    /// reads. It is deliberately NOT in <see cref="Reads"/>: everything there answers without a
    /// credential, and filing this beside them would have told this side it needs none. The
    /// bearer is a config key, which is not a grant token — it outlives the window and carries no
    /// port. Nullable with a fallback for the same reason every route here is.
    /// </remarks>
    public string ConfigReadRoutePath() =>
        ConfigRead is { Path.Length: > 0 } route ? route.Path : "/v1/config/read";

    /// <summary>
    /// The exit code for a named mechanism failure.
    /// </summary>
    /// <remarks>
    /// A name absent from the contract is a bug in this binary rather than in the caller's usage,
    /// so it answers <c>brokerFailure</c> instead of throwing: a CLI that crashed while trying to
    /// report a failure would tell an agent nothing at all.
    /// </remarks>
    public int Exit(string name) =>
        ExitCodes.TryGetValue(name, out var code) ? code : ExitCodes.GetValueOrDefault("brokerFailure", 95);
}

/// <summary>
/// One authenticated route, as the contract describes it.
/// </summary>
/// <remarks>
/// Its own shape rather than another entry in <see cref="BrokerContract.Reads"/>, because the
/// thing this side must not get wrong is that it needs a credential — and a bare path in a
/// dictionary of unauthenticated routes says the opposite.
/// </remarks>
public sealed record ConfigReadRoute(
    [property: JsonPropertyName("method")] string Method,
    [property: JsonPropertyName("path")] string Path,
    [property: JsonPropertyName("authenticated")] bool Authenticated,
    [property: JsonPropertyName("bearer")] string? Bearer);

/// <summary>
/// One route that answers without a credential and performs nothing.
/// </summary>
/// <remarks>
/// The same three fields as <see cref="HealthRoute"/>, and for the same reason: a second
/// implementation must be able to READ what verb to use rather than assume one. A bare path was
/// what let a listing be filed as a read and served as a POST.
/// </remarks>
public sealed record ReadEndpoint(
    [property: JsonPropertyName("method")] string Method,
    [property: JsonPropertyName("path")] string Path,
    [property: JsonPropertyName("authenticated")] bool Authenticated);

public sealed record HealthRoute(
    [property: JsonPropertyName("method")] string Method,
    [property: JsonPropertyName("path")] string Path,
    [property: JsonPropertyName("authenticated")] bool Authenticated);
